#!/usr/bin/env python3
"""
生成扩展的机场和航空公司数据库
运行: python generate_data.py
"""
import json, os

DATA_DIR = 'data'

# =====================================================================
# 全球机场数据库 — 约 900+ 机场
# 格式: IATA -> {name, name_en, city, city_en, country, country_en, lat, lon}
# =====================================================================
AIRPORTS = {
    # ======== 中国大陆 ========
    "PEK": {"name":"北京首都国际机场","name_en":"Beijing Capital Intl","city":"北京","city_en":"Beijing","country":"中国","country_en":"China","lat":40.0799,"lon":116.6031},
    "PKX": {"name":"北京大兴国际机场","name_en":"Beijing Daxing Intl","city":"北京","city_en":"Beijing","country":"中国","country_en":"China","lat":39.5098,"lon":116.4105},
    "SHA": {"name":"上海虹桥国际机场","name_en":"Shanghai Hongqiao Intl","city":"上海","city_en":"Shanghai","country":"中国","country_en":"China","lat":31.1979,"lon":121.3363},
    "PVG": {"name":"上海浦东国际机场","name_en":"Shanghai Pudong Intl","city":"上海","city_en":"Shanghai","country":"中国","country_en":"China","lat":31.1443,"lon":121.8083},
    "CAN": {"name":"广州白云国际机场","name_en":"Guangzhou Baiyun Intl","city":"广州","city_en":"Guangzhou","country":"中国","country_en":"China","lat":23.3924,"lon":113.2988},
    "SZX": {"name":"深圳宝安国际机场","name_en":"Shenzhen Bao'an Intl","city":"深圳","city_en":"Shenzhen","country":"中国","country_en":"China","lat":22.6393,"lon":113.8107},
    "CTU": {"name":"成都双流国际机场","name_en":"Chengdu Shuangliu Intl","city":"成都","city_en":"Chengdu","country":"中国","country_en":"China","lat":30.5785,"lon":103.9471},
    "TFU": {"name":"成都天府国际机场","name_en":"Chengdu Tianfu Intl","city":"成都","city_en":"Chengdu","country":"中国","country_en":"China","lat":30.3065,"lon":104.4469},
    "CKG": {"name":"重庆江北国际机场","name_en":"Chongqing Jiangbei Intl","city":"重庆","city_en":"Chongqing","country":"中国","country_en":"China","lat":29.7192,"lon":106.6417},
    "HGH": {"name":"杭州萧山国际机场","name_en":"Hangzhou Xiaoshan Intl","city":"杭州","city_en":"Hangzhou","country":"中国","country_en":"China","lat":30.2295,"lon":120.4344},
    "NKG": {"name":"南京禄口国际机场","name_en":"Nanjing Lukou Intl","city":"南京","city_en":"Nanjing","country":"中国","country_en":"China","lat":31.742,"lon":118.862},
    "XIY": {"name":"西安咸阳国际机场","name_en":"Xi'an Xianyang Intl","city":"西安","city_en":"Xi'an","country":"中国","country_en":"China","lat":34.4471,"lon":108.7516},
    "KMG": {"name":"昆明长水国际机场","name_en":"Kunming Changshui Intl","city":"昆明","city_en":"Kunming","country":"中国","country_en":"China","lat":25.1019,"lon":102.9292},
    "WUH": {"name":"武汉天河国际机场","name_en":"Wuhan Tianhe Intl","city":"武汉","city_en":"Wuhan","country":"中国","country_en":"China","lat":30.7838,"lon":114.2081},
    "CSX": {"name":"长沙黄花国际机场","name_en":"Changsha Huanghua Intl","city":"长沙","city_en":"Changsha","country":"中国","country_en":"China","lat":28.1892,"lon":113.22},
    "TAO": {"name":"青岛胶东国际机场","name_en":"Qingdao Jiaodong Intl","city":"青岛","city_en":"Qingdao","country":"中国","country_en":"China","lat":36.2611,"lon":120.1217},
    "TSN": {"name":"天津滨海国际机场","name_en":"Tianjin Binhai Intl","city":"天津","city_en":"Tianjin","country":"中国","country_en":"China","lat":39.1244,"lon":117.3462},
    "SYX": {"name":"三亚凤凰国际机场","name_en":"Sanya Phoenix Intl","city":"三亚","city_en":"Sanya","country":"中国","country_en":"China","lat":18.3029,"lon":109.4122},
    "HAK": {"name":"海口美兰国际机场","name_en":"Haikou Meilan Intl","city":"海口","city_en":"Haikou","country":"中国","country_en":"China","lat":19.9349,"lon":110.459},
    "DLC": {"name":"大连周水子国际机场","name_en":"Dalian Zhoushuizi Intl","city":"大连","city_en":"Dalian","country":"中国","country_en":"China","lat":38.9657,"lon":121.5386},
    "SHE": {"name":"沈阳桃仙国际机场","name_en":"Shenyang Taoxian Intl","city":"沈阳","city_en":"Shenyang","country":"中国","country_en":"China","lat":41.6398,"lon":123.4833},
    "HRB": {"name":"哈尔滨太平国际机场","name_en":"Harbin Taiping Intl","city":"哈尔滨","city_en":"Harbin","country":"中国","country_en":"China","lat":45.6234,"lon":126.2503},
    "CGQ": {"name":"长春龙嘉国际机场","name_en":"Changchun Longjia Intl","city":"长春","city_en":"Changchun","country":"中国","country_en":"China","lat":43.9962,"lon":125.6852},
    "URC": {"name":"乌鲁木齐地窝堡国际机场","name_en":"Urumqi Diwopu Intl","city":"乌鲁木齐","city_en":"Urumqi","country":"中国","country_en":"China","lat":43.9071,"lon":87.4742},
    "LHW": {"name":"兰州中川国际机场","name_en":"Lanzhou Zhongchuan Intl","city":"兰州","city_en":"Lanzhou","country":"中国","country_en":"China","lat":36.5152,"lon":103.6203},
    "XNN": {"name":"西宁曹家堡国际机场","name_en":"Xining Caojiabao Intl","city":"西宁","city_en":"Xining","country":"中国","country_en":"China","lat":36.5275,"lon":102.0433},
    "INC": {"name":"银川河东国际机场","name_en":"Yinchuan Hedong Intl","city":"银川","city_en":"Yinchuan","country":"中国","country_en":"China","lat":38.3219,"lon":106.3928},
    "HET": {"name":"呼和浩特白塔国际机场","name_en":"Hohhot Baita Intl","city":"呼和浩特","city_en":"Hohhot","country":"中国","country_en":"China","lat":40.8514,"lon":111.824},
    "TYN": {"name":"太原武宿国际机场","name_en":"Taiyuan Wusu Intl","city":"太原","city_en":"Taiyuan","country":"中国","country_en":"China","lat":37.7469,"lon":112.6283},
    "SJW": {"name":"石家庄正定国际机场","name_en":"Shijiazhuang Zhengding Intl","city":"石家庄","city_en":"Shijiazhuang","country":"中国","country_en":"China","lat":38.2807,"lon":114.6973},
    "FOC": {"name":"福州长乐国际机场","name_en":"Fuzhou Changle Intl","city":"福州","city_en":"Fuzhou","country":"中国","country_en":"China","lat":25.9351,"lon":119.6631},
    "XMN": {"name":"厦门高崎国际机场","name_en":"Xiamen Gaoqi Intl","city":"厦门","city_en":"Xiamen","country":"中国","country_en":"China","lat":24.544,"lon":118.1278},
    "NNG": {"name":"南宁吴圩国际机场","name_en":"Nanning Wuxu Intl","city":"南宁","city_en":"Nanning","country":"中国","country_en":"China","lat":22.6083,"lon":108.1722},
    "KWL": {"name":"桂林两江国际机场","name_en":"Guilin Liangjiang Intl","city":"桂林","city_en":"Guilin","country":"中国","country_en":"China","lat":25.2181,"lon":110.0392},
    "KWE": {"name":"贵阳龙洞堡国际机场","name_en":"Guiyang Longdongbao Intl","city":"贵阳","city_en":"Guiyang","country":"中国","country_en":"China","lat":26.5385,"lon":106.8017},
    "HFE": {"name":"合肥新桥国际机场","name_en":"Hefei Xinqiao Intl","city":"合肥","city_en":"Hefei","country":"中国","country_en":"China","lat":31.9880,"lon":116.9770},
    "NGB": {"name":"宁波栎社国际机场","name_en":"Ningbo Lishe Intl","city":"宁波","city_en":"Ningbo","country":"中国","country_en":"China","lat":29.8267,"lon":121.4622},
    "WNZ": {"name":"温州龙湾国际机场","name_en":"Wenzhou Longwan Intl","city":"温州","city_en":"Wenzhou","country":"中国","country_en":"China","lat":27.9122,"lon":120.8522},
    "YNT": {"name":"烟台蓬莱国际机场","name_en":"Yantai Penglai Intl","city":"烟台","city_en":"Yantai","country":"中国","country_en":"China","lat":37.6572,"lon":120.9872},
    "TNA": {"name":"济南遥墙国际机场","name_en":"Jinan Yaoqiang Intl","city":"济南","city_en":"Jinan","country":"中国","country_en":"China","lat":36.8572,"lon":117.2158},
    "CGO": {"name":"郑州新郑国际机场","name_en":"Zhengzhou Xinzheng Intl","city":"郑州","city_en":"Zhengzhou","country":"中国","country_en":"China","lat":34.5197,"lon":113.8408},
    "SWA": {"name":"揭阳潮汕国际机场","name_en":"Jieyang Chaoshan Intl","city":"汕头","city_en":"Shantou","country":"中国","country_en":"China","lat":23.4268,"lon":116.5053},
    "ZUH": {"name":"珠海金湾机场","name_en":"Zhuhai Jinwan Airport","city":"珠海","city_en":"Zhuhai","country":"中国","country_en":"China","lat":22.0064,"lon":113.3761},
    "LXA": {"name":"拉萨贡嘎机场","name_en":"Lhasa Gonggar Airport","city":"拉萨","city_en":"Lhasa","country":"中国","country_en":"China","lat":29.2978,"lon":90.9119},
    "JHG": {"name":"西双版纳嘎洒机场","name_en":"Xishuangbanna Gasa Airport","city":"西双版纳","city_en":"Xishuangbanna","country":"中国","country_en":"China","lat":21.9739,"lon":100.7600},
    "LJG": {"name":"丽江三义机场","name_en":"Lijiang Sanyi Airport","city":"丽江","city_en":"Lijiang","country":"中国","country_en":"China","lat":26.6822,"lon":100.2464},
    "DLU": {"name":"大理荒草坝机场","name_en":"Dali Huangcaoba Airport","city":"大理","city_en":"Dali","country":"中国","country_en":"China","lat":25.6494,"lon":100.3194},
    "KRL": {"name":"库尔勒梨城机场","name_en":"Korla Airport","city":"库尔勒","city_en":"Korla","country":"中国","country_en":"China","lat":41.6978,"lon":86.1289},
    "AKU": {"name":"阿克苏温宿机场","name_en":"Aksu Wensu Airport","city":"阿克苏","city_en":"Aksu","country":"中国","country_en":"China","lat":41.2625,"lon":80.2917},
    "KHG": {"name":"喀什机场","name_en":"Kashgar Airport","city":"喀什","city_en":"Kashgar","country":"中国","country_en":"China","lat":39.5429,"lon":76.0200},
    "HTN": {"name":"和田机场","name_en":"Hotan Airport","city":"和田","city_en":"Hotan","country":"中国","country_en":"China","lat":37.0385,"lon":79.8643},
    "YIH": {"name":"宜昌三峡机场","name_en":"Yichang Sanxia Airport","city":"宜昌","city_en":"Yichang","country":"中国","country_en":"China","lat":30.5565,"lon":111.4800},
    "ENH": {"name":"恩施许家坪机场","name_en":"Enshi Xujiaping Airport","city":"恩施","city_en":"Enshi","country":"中国","country_en":"China","lat":30.3203,"lon":109.4851},
    "WDS": {"name":"十堰武当山机场","name_en":"Shiyan Wudangshan Airport","city":"十堰","city_en":"Shiyan","country":"中国","country_en":"China","lat":32.5917,"lon":110.9078},
    "ZHA": {"name":"湛江机场","name_en":"Zhanjiang Airport","city":"湛江","city_en":"Zhanjiang","country":"中国","country_en":"China","lat":21.2144,"lon":110.3583},
    "MIG": {"name":"绵阳南郊机场","name_en":"Mianyang Nanjiao Airport","city":"绵阳","city_en":"Mianyang","country":"中国","country_en":"China","lat":31.4281,"lon":104.7417},
    "YBP": {"name":"宜宾五粮液机场","name_en":"Yibin Wuliangye Airport","city":"宜宾","city_en":"Yibin","country":"中国","country_en":"China","lat":28.8003,"lon":104.5453},
    "NAO": {"name":"南充高坪机场","name_en":"Nanchong Gaoping Airport","city":"南充","city_en":"Nanchong","country":"中国","country_en":"China","lat":30.7955,"lon":106.1626},
    "LZO": {"name":"泸州蓝田机场","name_en":"Luzhou Lantian Airport","city":"泸州","city_en":"Luzhou","country":"中国","country_en":"China","lat":28.8522,"lon":105.3931},
    "DAX": {"name":"达州河市机场","name_en":"Dazhou Heshi Airport","city":"达州","city_en":"Dazhou","country":"中国","country_en":"China","lat":31.1302,"lon":107.4295},
    "KOW": {"name":"赣州黄金机场","name_en":"Ganzhou Huangjin Airport","city":"赣州","city_en":"Ganzhou","country":"中国","country_en":"China","lat":25.8531,"lon":114.7789},
    "JDZ": {"name":"景德镇罗家机场","name_en":"Jingdezhen Luojia Airport","city":"景德镇","city_en":"Jingdezhen","country":"中国","country_en":"China","lat":29.3386,"lon":117.1764},
    "KHN": {"name":"南昌昌北国际机场","name_en":"Nanchang Changbei Intl","city":"南昌","city_en":"Nanchang","country":"中国","country_en":"China","lat":28.8650,"lon":115.9000},
    "WUX": {"name":"无锡苏南硕放国际机场","name_en":"Wuxi Sunan Shuofang Intl","city":"无锡","city_en":"Wuxi","country":"中国","country_en":"China","lat":31.4944,"lon":120.4294},
    "CZX": {"name":"常州奔牛国际机场","name_en":"Changzhou Benniu Intl","city":"常州","city_en":"Changzhou","country":"中国","country_en":"China","lat":31.9197,"lon":119.7789},
    "YNZ": {"name":"盐城南洋国际机场","name_en":"Yancheng Nanyang Intl","city":"盐城","city_en":"Yancheng","country":"中国","country_en":"China","lat":33.4258,"lon":120.2033},
    "NTG": {"name":"南通兴东国际机场","name_en":"Nantong Xingdong Intl","city":"南通","city_en":"Nantong","country":"中国","country_en":"China","lat":32.0708,"lon":120.9756},
    "XUZ": {"name":"徐州观音国际机场","name_en":"Xuzhou Guanyin Intl","city":"徐州","city_en":"Xuzhou","country":"中国","country_en":"China","lat":34.0591,"lon":117.5553},
    "LYA": {"name":"洛阳北郊机场","name_en":"Luoyang Beijiao Airport","city":"洛阳","city_en":"Luoyang","country":"中国","country_en":"China","lat":34.7411,"lon":112.3886},
    "BHY": {"name":"北海福成机场","name_en":"Beihai Fucheng Airport","city":"北海","city_en":"Beihai","country":"中国","country_en":"China","lat":21.5394,"lon":109.2939},
    "AEB": {"name":"百色巴马机场","name_en":"Baise Bama Airport","city":"百色","city_en":"Baise","country":"中国","country_en":"China","lat":23.7200,"lon":106.9600},
    "WEH": {"name":"威海大水泊机场","name_en":"Weihai Dashuibo Airport","city":"威海","city_en":"Weihai","country":"中国","country_en":"China","lat":37.1871,"lon":122.2292},
    "JNZ": {"name":"锦州小岭子机场","name_en":"Jinzhou Xiaolingzi Airport","city":"锦州","city_en":"Jinzhou","country":"中国","country_en":"China","lat":41.1014,"lon":121.0617},
    "MDG": {"name":"牡丹江海浪机场","name_en":"Mudanjiang Hailang Airport","city":"牡丹江","city_en":"Mudanjiang","country":"中国","country_en":"China","lat":44.5241,"lon":129.5689},
    "JMU": {"name":"佳木斯东郊机场","name_en":"Jiamusi Dongjiao Airport","city":"佳木斯","city_en":"Jiamusi","country":"中国","country_en":"China","lat":46.8434,"lon":130.4653},
    "HLD": {"name":"海拉尔东山机场","name_en":"Hailar Dongshan Airport","city":"呼伦贝尔","city_en":"Hulunbuir","country":"中国","country_en":"China","lat":49.2050,"lon":119.8250},
    "DSN": {"name":"鄂尔多斯伊金霍洛机场","name_en":"Ordos Ejin Horo Airport","city":"鄂尔多斯","city_en":"Ordos","country":"中国","country_en":"China","lat":39.4900,"lon":109.8614},
    "ZYI": {"name":"遵义茅台机场","name_en":"Zunyi Maotai Airport","city":"遵义","city_en":"Zunyi","country":"中国","country_en":"China","lat":27.5894,"lon":106.8333},
    "TEN": {"name":"铜仁凤凰机场","name_en":"Tongren Fenghuang Airport","city":"铜仁","city_en":"Tongren","country":"中国","country_en":"China","lat":27.8833,"lon":109.3089},
    "AVA": {"name":"安顺黄果树机场","name_en":"Anshun Huangguoshu Airport","city":"安顺","city_en":"Anshun","country":"中国","country_en":"China","lat":26.2606,"lon":105.8733},
    "ACX": {"name":"兴义万峰林机场","name_en":"Xingyi Wanfenglin Airport","city":"兴义","city_en":"Xingyi","country":"中国","country_en":"China","lat":25.0864,"lon":104.9592},
    "YIW": {"name":"义乌机场","name_en":"Yiwu Airport","city":"义乌","city_en":"Yiwu","country":"中国","country_en":"China","lat":29.3447,"lon":120.0319},
    "HSN": {"name":"舟山普陀山机场","name_en":"Zhoushan Putuoshan Airport","city":"舟山","city_en":"Zhoushan","country":"中国","country_en":"China","lat":29.9342,"lon":122.3622},
    "JJN": {"name":"泉州晋江机场","name_en":"Quanzhou Jinjiang Airport","city":"泉州","city_en":"Quanzhou","country":"中国","country_en":"China","lat":24.7964,"lon":118.5897},
    # ======== 港澳台 ========
    "HKG": {"name":"香港国际机场","name_en":"Hong Kong Intl","city":"香港","city_en":"Hong Kong","country":"中国","country_en":"China","lat":22.308,"lon":113.9185},
    "MFM": {"name":"澳门国际机场","name_en":"Macau Intl","city":"澳门","city_en":"Macau","country":"中国","country_en":"China","lat":22.1496,"lon":113.5915},
    "TPE": {"name":"台湾桃园国际机场","name_en":"Taiwan Taoyuan Intl","city":"台北","city_en":"Taipei","country":"中国","country_en":"China","lat":25.0797,"lon":121.2342},
    "TSA": {"name":"台北松山机场","name_en":"Taipei Songshan","city":"台北","city_en":"Taipei","country":"中国","country_en":"China","lat":25.0694,"lon":121.5525},
    "KHH": {"name":"高雄国际机场","name_en":"Kaohsiung Intl","city":"高雄","city_en":"Kaohsiung","country":"中国","country_en":"China","lat":22.5771,"lon":120.3499},
    "RMQ": {"name":"台中清泉岗机场","name_en":"Taichung Intl","city":"台中","city_en":"Taichung","country":"中国","country_en":"China","lat":24.2647,"lon":120.6209},
    "TNN": {"name":"台南机场","name_en":"Tainan Airport","city":"台南","city_en":"Tainan","country":"中国","country_en":"China","lat":22.9504,"lon":120.2057},
    # ======== 日本 ========
    "NRT": {"name":"东京成田国际机场","name_en":"Tokyo Narita Intl","city":"东京","city_en":"Tokyo","country":"日本","country_en":"Japan","lat":35.7647,"lon":140.3864},
    "HND": {"name":"东京羽田国际机场","name_en":"Tokyo Haneda Intl","city":"东京","city_en":"Tokyo","country":"日本","country_en":"Japan","lat":35.5494,"lon":139.7798},
    "KIX": {"name":"大阪关西国际机场","name_en":"Osaka Kansai Intl","city":"大阪","city_en":"Osaka","country":"日本","country_en":"Japan","lat":34.4347,"lon":135.244},
    "ITM": {"name":"大阪伊丹机场","name_en":"Osaka Itami","city":"大阪","city_en":"Osaka","country":"日本","country_en":"Japan","lat":34.7855,"lon":135.4381},
    "NGO": {"name":"名古屋中部国际机场","name_en":"Chubu Centrair Intl","city":"名古屋","city_en":"Nagoya","country":"日本","country_en":"Japan","lat":34.8584,"lon":136.8125},
    "CTS": {"name":"新千岁机场","name_en":"New Chitose Airport","city":"札幌","city_en":"Sapporo","country":"日本","country_en":"Japan","lat":42.7752,"lon":141.6925},
    "FUK": {"name":"福冈机场","name_en":"Fukuoka Airport","city":"福冈","city_en":"Fukuoka","country":"日本","country_en":"Japan","lat":33.5859,"lon":130.4511},
    "OKA": {"name":"那霸机场","name_en":"Naha Airport","city":"那霸","city_en":"Naha","country":"日本","country_en":"Japan","lat":26.1958,"lon":127.646},
    "KOJ": {"name":"�的场机场","name_en":"Kagoshima Airport","city":"鹿儿岛","city_en":"Kagoshima","country":"日本","country_en":"Japan","lat":31.8034,"lon":130.7197},
    "HIJ": {"name":"广岛机场","name_en":"Hiroshima Airport","city":"广岛","city_en":"Hiroshima","country":"日本","country_en":"Japan","lat":34.4361,"lon":132.9194},
    "SDJ": {"name":"仙台机场","name_en":"Sendai Airport","city":"仙台","city_en":"Sendai","country":"日本","country_en":"Japan","lat":38.1397,"lon":140.917},
    "KMJ": {"name":"熊本机场","name_en":"Kumamoto Airport","city":"熊本","city_en":"Kumamoto","country":"日本","country_en":"Japan","lat":32.8373,"lon":130.8551},
    "NGS": {"name":"长崎机场","name_en":"Nagasaki Airport","city":"长崎","city_en":"Nagasaki","country":"日本","country_en":"Japan","lat":32.9169,"lon":129.9136},
    "OIT": {"name":"大分机场","name_en":"Oita Airport","city":"大分","city_en":"Oita","country":"日本","country_en":"Japan","lat":33.4794,"lon":131.7372},
    "MYJ": {"name":"松山机场","name_en":"Matsuyama Airport","city":"松山","city_en":"Matsuyama","country":"日本","country_en":"Japan","lat":33.8272,"lon":132.6997},
    "TAK": {"name":"高松机场","name_en":"Takamatsu Airport","city":"高松","city_en":"Takamatsu","country":"日本","country_en":"Japan","lat":34.2142,"lon":134.0156},
    "KMQ": {"name":"小松机场","name_en":"Komatsu Airport","city":"小松","city_en":"Komatsu","country":"日本","country_en":"Japan","lat":36.3946,"lon":136.4068},
    "NKM": {"name":"名古屋小牧机场","name_en":"Nagoya Komaki","city":"名古屋","city_en":"Nagoya","country":"日本","country_en":"Japan","lat":35.2551,"lon":136.9240},
    "AOJ": {"name":"青森机场","name_en":"Aomori Airport","city":"青森","city_en":"Aomori","country":"日本","country_en":"Japan","lat":40.7347,"lon":140.6908},
    "AKJ": {"name":"旭川机场","name_en":"Asahikawa Airport","city":"旭川","city_en":"Asahikawa","country":"日本","country_en":"Japan","lat":43.6708,"lon":142.4475},
    "OKJ": {"name":"冈山机场","name_en":"Okayama Airport","city":"冈山","city_en":"Okayama","country":"日本","country_en":"Japan","lat":34.7569,"lon":133.8553},
    "ISG": {"name":"石垣机场","name_en":"Ishigaki Airport","city":"石垣","city_en":"Ishigaki","country":"日本","country_en":"Japan","lat":24.3964,"lon":124.2450},
    "MMY": {"name":"宫古机场","name_en":"Miyako Airport","city":"宫古","city_en":"Miyako","country":"日本","country_en":"Japan","lat":24.7828,"lon":125.2950},
    # ======== 韩国 ========
    "ICN": {"name":"仁川国际机场","name_en":"Incheon Intl","city":"首尔","city_en":"Seoul","country":"韩国","country_en":"South Korea","lat":37.4602,"lon":126.4407},
    "GMP": {"name":"金浦国际机场","name_en":"Gimpo Intl","city":"首尔","city_en":"Seoul","country":"韩国","country_en":"South Korea","lat":37.5583,"lon":126.7906},
    "PUS": {"name":"釜山金海国际机场","name_en":"Busan Gimhae Intl","city":"釜山","city_en":"Busan","country":"韩国","country_en":"South Korea","lat":35.1796,"lon":128.9381},
    "CJU": {"name":"济州国际机场","name_en":"Jeju Intl","city":"济州","city_en":"Jeju","country":"韩国","country_en":"South Korea","lat":33.5113,"lon":126.4928},
    "TAE": {"name":"大邱国际机场","name_en":"Daegu Intl","city":"大邱","city_en":"Daegu","country":"韩国","country_en":"South Korea","lat":35.8941,"lon":128.6589},
    "CJJ": {"name":"清州国际机场","name_en":"Cheongju Intl","city":"清州","city_en":"Cheongju","country":"韩国","country_en":"South Korea","lat":36.7166,"lon":127.499},
    "MWX": {"name":"务安国际机场","name_en":"Muan Intl","city":"务安","city_en":"Muan","country":"韩国","country_en":"South Korea","lat":34.9914,"lon":126.3828},
    "RSU": {"name":"丽水机场","name_en":"Yeosu Airport","city":"丽水","city_en":"Yeosu","country":"韩国","country_en":"South Korea","lat":34.8423,"lon":127.6169},
    "KWJ": {"name":"光州机场","name_en":"Gwangju Airport","city":"光州","city_en":"Gwangju","country":"韩国","country_en":"South Korea","lat":35.1264,"lon":126.8089},
    # ======== 东南亚 ========
    "SIN": {"name":"新加坡樟宜机场","name_en":"Singapore Changi","city":"新加坡","city_en":"Singapore","country":"新加坡","country_en":"Singapore","lat":1.3644,"lon":103.9915},
    "BKK": {"name":"曼谷素万那普机场","name_en":"Bangkok Suvarnabhumi","city":"曼谷","city_en":"Bangkok","country":"泰国","country_en":"Thailand","lat":13.6900,"lon":100.7501},
    "DMK": {"name":"曼谷廊曼机场","name_en":"Bangkok Don Mueang","city":"曼谷","city_en":"Bangkok","country":"泰国","country_en":"Thailand","lat":13.9126,"lon":100.6069},
    "CNX": {"name":"清迈国际机场","name_en":"Chiang Mai Intl","city":"清迈","city_en":"Chiang Mai","country":"泰国","country_en":"Thailand","lat":18.7668,"lon":98.9625},
    "HKT": {"name":"普吉国际机场","name_en":"Phuket Intl","city":"普吉","city_en":"Phuket","country":"泰国","country_en":"Thailand","lat":8.1132,"lon":98.3169},
    "USM": {"name":"苏梅岛机场","name_en":"Koh Samui Airport","city":"苏梅岛","city_en":"Koh Samui","country":"泰国","country_en":"Thailand","lat":9.5478,"lon":100.0623},
    "CEI": {"name":"清莱机场","name_en":"Chiang Rai Airport","city":"清莱","city_en":"Chiang Rai","country":"泰国","country_en":"Thailand","lat":19.9523,"lon":99.8828},
    "KBV": {"name":"甲米机场","name_en":"Krabi Airport","city":"甲米","city_en":"Krabi","country":"泰国","country_en":"Thailand","lat":8.0961,"lon":98.9862},
    "KUL": {"name":"吉隆坡国际机场","name_en":"Kuala Lumpur Intl","city":"吉隆坡","city_en":"Kuala Lumpur","country":"马来西亚","country_en":"Malaysia","lat":2.7456,"lon":101.7099},
    "SZB": {"name":"梳邦苏丹阿卜杜勒阿齐兹沙机场","name_en":"Sultan Abdul Aziz Shah","city":"吉隆坡","city_en":"Kuala Lumpur","country":"马来西亚","country_en":"Malaysia","lat":3.1304,"lon":101.5492},
    "PEN": {"name":"槟城国际机场","name_en":"Penang Intl","city":"槟城","city_en":"Penang","country":"马来西亚","country_en":"Malaysia","lat":5.2971,"lon":100.2769},
    "BKI": {"name":"亚庇国际机场","name_en":"Kota Kinabalu Intl","city":"亚庇","city_en":"Kota Kinabalu","country":"马来西亚","country_en":"Malaysia","lat":5.9372,"lon":116.0505},
    "KCH": {"name":"古晋国际机场","name_en":"Kuching Intl","city":"古晋","city_en":"Kuching","country":"马来西亚","country_en":"Malaysia","lat":1.4847,"lon":110.3472},
    "LGK": {"name":"兰卡威国际机场","name_en":"Langkawi Intl","city":"兰卡威","city_en":"Langkawi","country":"马来西亚","country_en":"Malaysia","lat":6.3297,"lon":99.7286},
    "JHB": {"name":"新山士乃国际机场","name_en":"Johor Bahru Senai Intl","city":"新山","city_en":"Johor Bahru","country":"马来西亚","country_en":"Malaysia","lat":1.6412,"lon":103.6697},
    "SGN": {"name":"胡志明市新山一机场","name_en":"Ho Chi Minh Tan Son Nhat","city":"胡志明市","city_en":"Ho Chi Minh City","country":"越南","country_en":"Vietnam","lat":10.8188,"lon":106.6520},
    "HAN": {"name":"河内内排机场","name_en":"Hanoi Noi Bai","city":"河内","city_en":"Hanoi","country":"越南","country_en":"Vietnam","lat":21.2212,"lon":105.807},
    "DAD": {"name":"岘港国际机场","name_en":"Da Nang Intl","city":"岘港","city_en":"Da Nang","country":"越南","country_en":"Vietnam","lat":16.0439,"lon":108.1992},
    "CXR": {"name":"芽庄金兰机场","name_en":"Nha Trang Cam Ranh","city":"芽庄","city_en":"Nha Trang","country":"越南","country_en":"Vietnam","lat":11.9982,"lon":109.2194},
    "PQC": {"name":"富国岛机场","name_en":"Phu Quoc Intl","city":"富国岛","city_en":"Phu Quoc","country":"越南","country_en":"Vietnam","lat":10.1698,"lon":103.9930},
    "DPS": {"name":"巴厘岛伍拉·赖机场","name_en":"Bali Ngurah Rai","city":"巴厘岛","city_en":"Bali","country":"印度尼西亚","country_en":"Indonesia","lat":-8.7482,"lon":115.1672},
    "CGK": {"name":"雅加达苏加诺-哈达机场","name_en":"Jakarta Soekarno-Hatta","city":"雅加达","city_en":"Jakarta","country":"印度尼西亚","country_en":"Indonesia","lat":-6.1256,"lon":106.6559},
    "SUB": {"name":"泗水朱安达机场","name_en":"Surabaya Juanda","city":"泗水","city_en":"Surabaya","country":"印度尼西亚","country_en":"Indonesia","lat":-7.3798,"lon":112.7868},
    "JOG": {"name":"日惹阿迪苏奇普托机场","name_en":"Yogyakarta Adisucipto","city":"日惹","city_en":"Yogyakarta","country":"印度尼西亚","country_en":"Indonesia","lat":-7.7882,"lon":110.4317},
    "UPG": {"name":"望加锡苏丹哈桑丁机场","name_en":"Makassar Sultan Hasanuddin","city":"望加锡","city_en":"Makassar","country":"印度尼西亚","country_en":"Indonesia","lat":-5.0616,"lon":119.5540},
    "MNL": {"name":"马尼拉尼诺·阿基诺机场","name_en":"Manila Ninoy Aquino Intl","city":"马尼拉","city_en":"Manila","country":"菲律宾","country_en":"Philippines","lat":14.5086,"lon":121.0198},
    "CEB": {"name":"宿务麦克坦机场","name_en":"Cebu Mactan Intl","city":"宿务","city_en":"Cebu","country":"菲律宾","country_en":"Philippines","lat":10.3075,"lon":123.9794},
    "CRK": {"name":"克拉克国际机场","name_en":"Clark Intl","city":"克拉克","city_en":"Clark","country":"菲律宾","country_en":"Philippines","lat":15.186,"lon":120.56},
    "DVO": {"name":"达沃国际机场","name_en":"Davao Intl","city":"达沃","city_en":"Davao","country":"菲律宾","country_en":"Philippines","lat":7.1255,"lon":125.6456},
    "PNH": {"name":"金边国际机场","name_en":"Phnom Penh Intl","city":"金边","city_en":"Phnom Penh","country":"柬埔寨","country_en":"Cambodia","lat":11.5466,"lon":104.8441},
    "REP": {"name":"暹粒国际机场","name_en":"Siem Reap Intl","city":"暹粒","city_en":"Siem Reap","country":"柬埔寨","country_en":"Cambodia","lat":13.4107,"lon":103.8128},
    "RGN": {"name":"仰光国际机场","name_en":"Yangon Intl","city":"仰光","city_en":"Yangon","country":"缅甸","country_en":"Myanmar","lat":16.9073,"lon":96.1332},
    "MDL": {"name":"曼德勒国际机场","name_en":"Mandalay Intl","city":"曼德勒","city_en":"Mandalay","country":"缅甸","country_en":"Myanmar","lat":21.7022,"lon":95.9778},
    "VTE": {"name":"万象瓦岱机场","name_en":"Vientiane Wattay","city":"万象","city_en":"Vientiane","country":"老挝","country_en":"Laos","lat":17.9883,"lon":102.5633},
    "LPQ": {"name":"琅勃拉邦机场","name_en":"Luang Prabang","city":"琅勃拉邦","city_en":"Luang Prabang","country":"老挝","country_en":"Laos","lat":19.8972,"lon":102.1608},
    "BWN": {"name":"文莱国际机场","name_en":"Brunei Intl","city":"斯里巴加湾","city_en":"Bandar Seri Begawan","country":"文莱","country_en":"Brunei","lat":4.9442,"lon":114.9283},
    # ======== 南亚 ========
    "DEL": {"name":"新德里英迪拉·甘地机场","name_en":"Delhi Indira Gandhi Intl","city":"新德里","city_en":"New Delhi","country":"印度","country_en":"India","lat":28.5562,"lon":77.1},
    "BOM": {"name":"孟买贾特拉帕蒂·希瓦吉机场","name_en":"Mumbai Chhatrapati Shivaji","city":"孟买","city_en":"Mumbai","country":"印度","country_en":"India","lat":19.0896,"lon":72.8656},
    "BLR": {"name":"班加罗尔机场","name_en":"Bengaluru Kempegowda Intl","city":"班加罗尔","city_en":"Bengaluru","country":"印度","country_en":"India","lat":13.1986,"lon":77.7066},
    "MAA": {"name":"金奈机场","name_en":"Chennai Intl","city":"金奈","city_en":"Chennai","country":"印度","country_en":"India","lat":12.9941,"lon":80.1709},
    "HYD": {"name":"海德拉巴机场","name_en":"Hyderabad Rajiv Gandhi Intl","city":"海德拉巴","city_en":"Hyderabad","country":"印度","country_en":"India","lat":17.2403,"lon":78.4294},
    "CCU": {"name":"加尔各答机场","name_en":"Kolkata Netaji Subhas Chandra Bose","city":"加尔各答","city_en":"Kolkata","country":"印度","country_en":"India","lat":22.6547,"lon":88.4467},
    "COK": {"name":"科钦机场","name_en":"Cochin Intl","city":"科钦","city_en":"Kochi","country":"印度","country_en":"India","lat":10.152,"lon":76.4019},
    "GOI": {"name":"果阿机场","name_en":"Goa Manohar Intl","city":"果阿","city_en":"Goa","country":"印度","country_en":"India","lat":15.3808,"lon":73.8314},
    "AMD": {"name":"艾哈迈达巴德机场","name_en":"Ahmedabad Sardar Vallabhbhai Patel","city":"艾哈迈达巴德","city_en":"Ahmedabad","country":"印度","country_en":"India","lat":23.0772,"lon":72.6347},
    "CMB": {"name":"科伦坡班达拉奈克机场","name_en":"Colombo Bandaranaike","city":"科伦坡","city_en":"Colombo","country":"斯里兰卡","country_en":"Sri Lanka","lat":7.1808,"lon":79.8841},
    "KTM": {"name":"加德满都特里布万机场","name_en":"Kathmandu Tribhuvan","city":"加德满都","city_en":"Kathmandu","country":"尼泊尔","country_en":"Nepal","lat":27.6966,"lon":85.3591},
    "DAC": {"name":"达卡沙阿贾拉勒机场","name_en":"Dhaka Hazrat Shahjalal","city":"达卡","city_en":"Dhaka","country":"孟加拉","country_en":"Bangladesh","lat":23.8433,"lon":90.3978},
    "MLE": {"name":"马尔代夫维拉纳机场","name_en":"Malé Velana Intl","city":"马累","city_en":"Malé","country":"马尔代夫","country_en":"Maldives","lat":4.1918,"lon":73.5291},
    "ISB": {"name":"伊斯兰堡国际机场","name_en":"Islamabad Intl","city":"伊斯兰堡","city_en":"Islamabad","country":"巴基斯坦","country_en":"Pakistan","lat":33.5607,"lon":72.8496},
    "KHI": {"name":"卡拉奇真纳机场","name_en":"Karachi Jinnah Intl","city":"卡拉奇","city_en":"Karachi","country":"巴基斯坦","country_en":"Pakistan","lat":24.9065,"lon":67.1608},
    "LHE": {"name":"拉合尔阿拉马伊克巴勒机场","name_en":"Lahore Allama Iqbal Intl","city":"拉合尔","city_en":"Lahore","country":"巴基斯坦","country_en":"Pakistan","lat":31.5216,"lon":74.4036},
    # ======== 中东 ========
    "DXB": {"name":"迪拜国际机场","name_en":"Dubai Intl","city":"迪拜","city_en":"Dubai","country":"阿联酋","country_en":"UAE","lat":25.2532,"lon":55.3657},
    "DWC": {"name":"迪拜阿勒马克图姆机场","name_en":"Dubai Al Maktoum Intl","city":"迪拜","city_en":"Dubai","country":"阿联酋","country_en":"UAE","lat":24.8966,"lon":55.1614},
    "AUH": {"name":"阿布扎比国际机场","name_en":"Abu Dhabi Intl","city":"阿布扎比","city_en":"Abu Dhabi","country":"阿联酋","country_en":"UAE","lat":24.4330,"lon":54.6511},
    "SHJ": {"name":"沙迦国际机场","name_en":"Sharjah Intl","city":"沙迦","city_en":"Sharjah","country":"阿联酋","country_en":"UAE","lat":25.3286,"lon":55.5172},
    "DOH": {"name":"多哈哈马德国际机场","name_en":"Doha Hamad Intl","city":"多哈","city_en":"Doha","country":"卡塔尔","country_en":"Qatar","lat":25.2609,"lon":51.6138},
    "BAH": {"name":"巴林国际机场","name_en":"Bahrain Intl","city":"麦纳麦","city_en":"Manama","country":"巴林","country_en":"Bahrain","lat":26.2708,"lon":50.6336},
    "MCT": {"name":"马斯喀特国际机场","name_en":"Muscat Intl","city":"马斯喀特","city_en":"Muscat","country":"阿曼","country_en":"Oman","lat":23.5933,"lon":58.2844},
    "KWI": {"name":"科威特国际机场","name_en":"Kuwait Intl","city":"科威特","city_en":"Kuwait City","country":"科威特","country_en":"Kuwait","lat":29.2267,"lon":47.9689},
    "RUH": {"name":"利雅得哈立德国王机场","name_en":"Riyadh King Khalid Intl","city":"利雅得","city_en":"Riyadh","country":"沙特阿拉伯","country_en":"Saudi Arabia","lat":24.9578,"lon":46.6989},
    "JED": {"name":"吉达阿卜杜勒阿齐兹国王机场","name_en":"Jeddah King Abdulaziz Intl","city":"吉达","city_en":"Jeddah","country":"沙特阿拉伯","country_en":"Saudi Arabia","lat":21.6706,"lon":39.1505},
    "DMM": {"name":"达曼法赫德国王机场","name_en":"Dammam King Fahd Intl","city":"达曼","city_en":"Dammam","country":"沙特阿拉伯","country_en":"Saudi Arabia","lat":26.4712,"lon":49.7979},
    "MED": {"name":"麦地那穆罕默德王子机场","name_en":"Medina Prince Mohammad Bin Abdulaziz","city":"麦地那","city_en":"Medina","country":"沙特阿拉伯","country_en":"Saudi Arabia","lat":24.5534,"lon":39.7051},
    "IST": {"name":"伊斯坦布尔机场","name_en":"Istanbul Airport","city":"伊斯坦布尔","city_en":"Istanbul","country":"土耳其","country_en":"Turkey","lat":41.2753,"lon":28.7519},
    "SAW": {"name":"伊斯坦布尔萨比哈格克琴机场","name_en":"Istanbul Sabiha Gokcen","city":"伊斯坦布尔","city_en":"Istanbul","country":"土耳其","country_en":"Turkey","lat":40.8986,"lon":29.3092},
    "AYT": {"name":"安塔利亚机场","name_en":"Antalya Airport","city":"安塔利亚","city_en":"Antalya","country":"土耳其","country_en":"Turkey","lat":36.8987,"lon":30.8005},
    "ESB": {"name":"安卡拉埃森博阿机场","name_en":"Ankara Esenboga","city":"安卡拉","city_en":"Ankara","country":"土耳其","country_en":"Turkey","lat":40.1281,"lon":32.9951},
    "ADB": {"name":"伊兹密尔阿德南曼德列斯机场","name_en":"Izmir Adnan Menderes","city":"伊兹密尔","city_en":"Izmir","country":"土耳其","country_en":"Turkey","lat":38.2924,"lon":27.157},
    "TLV": {"name":"特拉维夫本古里安机场","name_en":"Tel Aviv Ben Gurion","city":"特拉维夫","city_en":"Tel Aviv","country":"以色列","country_en":"Israel","lat":32.0114,"lon":34.8867},
    "AMM": {"name":"安曼阿利亚王后机场","name_en":"Amman Queen Alia Intl","city":"安曼","city_en":"Amman","country":"约旦","country_en":"Jordan","lat":31.7226,"lon":35.9932},
    "BEY": {"name":"贝鲁特哈里里机场","name_en":"Beirut Rafic Hariri Intl","city":"贝鲁特","city_en":"Beirut","country":"黎巴嫩","country_en":"Lebanon","lat":33.8209,"lon":35.4884},
    # ======== 欧洲 ========
    "LHR": {"name":"伦敦希思罗机场","name_en":"London Heathrow","city":"伦敦","city_en":"London","country":"英国","country_en":"United Kingdom","lat":51.4700,"lon":-0.4543},
    "LGW": {"name":"伦敦盖特威克机场","name_en":"London Gatwick","city":"伦敦","city_en":"London","country":"英国","country_en":"United Kingdom","lat":51.1537,"lon":-0.1821},
    "STN": {"name":"伦敦斯坦斯特德机场","name_en":"London Stansted","city":"伦敦","city_en":"London","country":"英国","country_en":"United Kingdom","lat":51.885,"lon":0.235},
    "LTN": {"name":"伦敦卢顿机场","name_en":"London Luton","city":"伦敦","city_en":"London","country":"英国","country_en":"United Kingdom","lat":51.8747,"lon":-0.3683},
    "LCY": {"name":"伦敦城市机场","name_en":"London City","city":"伦敦","city_en":"London","country":"英国","country_en":"United Kingdom","lat":51.5048,"lon":0.0495},
    "MAN": {"name":"曼彻斯特机场","name_en":"Manchester Airport","city":"曼彻斯特","city_en":"Manchester","country":"英国","country_en":"United Kingdom","lat":53.3537,"lon":-2.275},
    "EDI": {"name":"爱丁堡机场","name_en":"Edinburgh Airport","city":"爱丁堡","city_en":"Edinburgh","country":"英国","country_en":"United Kingdom","lat":55.9508,"lon":-3.3725},
    "BHX": {"name":"伯明翰机场","name_en":"Birmingham Airport","city":"伯明翰","city_en":"Birmingham","country":"英国","country_en":"United Kingdom","lat":52.4539,"lon":-1.7480},
    "BRS": {"name":"布里斯托尔机场","name_en":"Bristol Airport","city":"布里斯托尔","city_en":"Bristol","country":"英国","country_en":"United Kingdom","lat":51.3827,"lon":-2.7191},
    "GLA": {"name":"格拉斯哥机场","name_en":"Glasgow Airport","city":"格拉斯哥","city_en":"Glasgow","country":"英国","country_en":"United Kingdom","lat":55.8642,"lon":-4.4331},
    "CDG": {"name":"巴黎戴高乐机场","name_en":"Paris Charles de Gaulle","city":"巴黎","city_en":"Paris","country":"法国","country_en":"France","lat":49.0097,"lon":2.5479},
    "ORY": {"name":"巴黎奥利机场","name_en":"Paris Orly","city":"巴黎","city_en":"Paris","country":"法国","country_en":"France","lat":48.7262,"lon":2.3652},
    "NCE": {"name":"尼斯蔚蓝海岸机场","name_en":"Nice Côte d'Azur","city":"尼斯","city_en":"Nice","country":"法国","country_en":"France","lat":43.6584,"lon":7.2159},
    "LYS": {"name":"里昂圣埃克絮佩里机场","name_en":"Lyon Saint-Exupéry","city":"里昂","city_en":"Lyon","country":"法国","country_en":"France","lat":45.7256,"lon":5.0811},
    "MRS": {"name":"马赛普罗旺斯机场","name_en":"Marseille Provence","city":"马赛","city_en":"Marseille","country":"法国","country_en":"France","lat":43.4392,"lon":5.2214},
    "TLS": {"name":"图卢兹布拉尼亚克机场","name_en":"Toulouse Blagnac","city":"图卢兹","city_en":"Toulouse","country":"法国","country_en":"France","lat":43.6291,"lon":1.3638},
    "BOD": {"name":"波尔多梅里尼亚克机场","name_en":"Bordeaux Mérignac","city":"波尔多","city_en":"Bordeaux","country":"法国","country_en":"France","lat":44.8283,"lon":-0.7156},
    "FRA": {"name":"法兰克福机场","name_en":"Frankfurt Airport","city":"法兰克福","city_en":"Frankfurt","country":"德国","country_en":"Germany","lat":50.0379,"lon":8.5622},
    "MUC": {"name":"慕尼黑机场","name_en":"Munich Airport","city":"慕尼黑","city_en":"Munich","country":"德国","country_en":"Germany","lat":48.3538,"lon":11.7861},
    "TXL": {"name":"柏林机场","name_en":"Berlin Brandenburg","city":"柏林","city_en":"Berlin","country":"德国","country_en":"Germany","lat":52.362,"lon":13.509},
    "BER": {"name":"柏林勃兰登堡机场","name_en":"Berlin Brandenburg","city":"柏林","city_en":"Berlin","country":"德国","country_en":"Germany","lat":52.3667,"lon":13.5033},
    "DUS": {"name":"杜塞尔多夫机场","name_en":"Düsseldorf Airport","city":"杜塞尔多夫","city_en":"Düsseldorf","country":"德国","country_en":"Germany","lat":51.2895,"lon":6.7668},
    "HAM": {"name":"汉堡机场","name_en":"Hamburg Airport","city":"汉堡","city_en":"Hamburg","country":"德国","country_en":"Germany","lat":53.6304,"lon":9.9882},
    "CGN": {"name":"科隆/波恩机场","name_en":"Cologne Bonn","city":"科隆","city_en":"Cologne","country":"德国","country_en":"Germany","lat":50.8659,"lon":7.1427},
    "STR": {"name":"斯图加特机场","name_en":"Stuttgart Airport","city":"斯图加特","city_en":"Stuttgart","country":"德国","country_en":"Germany","lat":48.6899,"lon":9.2220},
    "AMS": {"name":"阿姆斯特丹史基浦机场","name_en":"Amsterdam Schiphol","city":"阿姆斯特丹","city_en":"Amsterdam","country":"荷兰","country_en":"Netherlands","lat":52.3105,"lon":4.7683},
    "BRU": {"name":"布鲁塞尔机场","name_en":"Brussels Airport","city":"布鲁塞尔","city_en":"Brussels","country":"比利时","country_en":"Belgium","lat":50.9014,"lon":4.4844},
    "LUX": {"name":"卢森堡机场","name_en":"Luxembourg Airport","city":"卢森堡","city_en":"Luxembourg","country":"卢森堡","country_en":"Luxembourg","lat":49.6233,"lon":6.2044},
    "ZRH": {"name":"苏黎世机场","name_en":"Zürich Airport","city":"苏黎世","city_en":"Zurich","country":"瑞士","country_en":"Switzerland","lat":47.4647,"lon":8.5492},
    "GVA": {"name":"日内瓦机场","name_en":"Geneva Airport","city":"日内瓦","city_en":"Geneva","country":"瑞士","country_en":"Switzerland","lat":46.238,"lon":6.1089},
    "BSL": {"name":"巴塞尔-米卢斯-弗赖堡机场","name_en":"Basel Mulhouse Freiburg","city":"巴塞尔","city_en":"Basel","country":"瑞士","country_en":"Switzerland","lat":47.5896,"lon":7.5299},
    "VIE": {"name":"维也纳机场","name_en":"Vienna Intl","city":"维也纳","city_en":"Vienna","country":"奥地利","country_en":"Austria","lat":48.1103,"lon":16.5697},
    "MAD": {"name":"马德里巴拉哈斯机场","name_en":"Madrid Barajas","city":"马德里","city_en":"Madrid","country":"西班牙","country_en":"Spain","lat":40.4936,"lon":-3.5668},
    "BCN": {"name":"巴塞罗那埃尔普拉特机场","name_en":"Barcelona El Prat","city":"巴塞罗那","city_en":"Barcelona","country":"西班牙","country_en":"Spain","lat":41.2971,"lon":2.0785},
    "AGP": {"name":"马拉加机场","name_en":"Málaga Airport","city":"马拉加","city_en":"Málaga","country":"西班牙","country_en":"Spain","lat":36.6749,"lon":-4.4991},
    "PMI": {"name":"帕尔马德马略卡机场","name_en":"Palma de Mallorca","city":"帕尔马","city_en":"Palma","country":"西班牙","country_en":"Spain","lat":39.5517,"lon":2.7388},
    "ALC": {"name":"阿利坎特机场","name_en":"Alicante Airport","city":"阿利坎特","city_en":"Alicante","country":"西班牙","country_en":"Spain","lat":38.2822,"lon":-0.5582},
    "VLC": {"name":"巴伦西亚机场","name_en":"Valencia Airport","city":"巴伦西亚","city_en":"Valencia","country":"西班牙","country_en":"Spain","lat":39.4893,"lon":-0.4816},
    "TFS": {"name":"特内里费南部机场","name_en":"Tenerife South","city":"特内里费","city_en":"Tenerife","country":"西班牙","country_en":"Spain","lat":28.0445,"lon":-16.5725},
    "LIS": {"name":"里斯本机场","name_en":"Lisbon Humberto Delgado","city":"里斯本","city_en":"Lisbon","country":"葡萄牙","country_en":"Portugal","lat":38.7742,"lon":-9.1342},
    "OPO": {"name":"波尔图机场","name_en":"Porto Francisco Sá Carneiro","city":"波尔图","city_en":"Porto","country":"葡萄牙","country_en":"Portugal","lat":41.2481,"lon":-8.6814},
    "FCO": {"name":"罗马菲乌米奇诺机场","name_en":"Rome Fiumicino","city":"罗马","city_en":"Rome","country":"意大利","country_en":"Italy","lat":41.8003,"lon":12.2389},
    "MXP": {"name":"米兰马尔彭萨机场","name_en":"Milan Malpensa","city":"米兰","city_en":"Milan","country":"意大利","country_en":"Italy","lat":45.6306,"lon":8.7281},
    "LIN": {"name":"米兰利纳特机场","name_en":"Milan Linate","city":"米兰","city_en":"Milan","country":"意大利","country_en":"Italy","lat":45.4494,"lon":9.2783},
    "VCE": {"name":"威尼斯马可波罗机场","name_en":"Venice Marco Polo","city":"威尼斯","city_en":"Venice","country":"意大利","country_en":"Italy","lat":45.5053,"lon":12.3519},
    "NAP": {"name":"那不勒斯机场","name_en":"Naples Intl","city":"那不勒斯","city_en":"Naples","country":"意大利","country_en":"Italy","lat":40.886,"lon":14.2908},
    "FLR": {"name":"佛罗伦萨机场","name_en":"Florence Airport","city":"佛罗伦萨","city_en":"Florence","country":"意大利","country_en":"Italy","lat":43.8100,"lon":11.2051},
    "ATH": {"name":"雅典机场","name_en":"Athens Eleftherios Venizelos","city":"雅典","city_en":"Athens","country":"希腊","country_en":"Greece","lat":37.9364,"lon":23.9445},
    "SKG": {"name":"塞萨洛尼基机场","name_en":"Thessaloniki Macedonia","city":"塞萨洛尼基","city_en":"Thessaloniki","country":"希腊","country_en":"Greece","lat":40.5197,"lon":22.9709},
    "HER": {"name":"伊拉克利翁机场","name_en":"Heraklion Nikos Kazantzakis","city":"伊拉克利翁","city_en":"Heraklion","country":"希腊","country_en":"Greece","lat":35.3397,"lon":25.1803},
    "JMK": {"name":"米科诺斯机场","name_en":"Mykonos Airport","city":"米科诺斯","city_en":"Mykonos","country":"希腊","country_en":"Greece","lat":37.4351,"lon":25.3481},
    "JTR": {"name":"圣托里尼机场","name_en":"Santorini Airport","city":"圣托里尼","city_en":"Santorini","country":"希腊","country_en":"Greece","lat":36.3992,"lon":25.4793},
    "CPH": {"name":"哥本哈根机场","name_en":"Copenhagen Kastrup","city":"哥本哈根","city_en":"Copenhagen","country":"丹麦","country_en":"Denmark","lat":55.618,"lon":12.656},
    "OSL": {"name":"奥斯陆加勒穆恩机场","name_en":"Oslo Gardermoen","city":"奥斯陆","city_en":"Oslo","country":"挪威","country_en":"Norway","lat":60.1976,"lon":11.1004},
    "BGO": {"name":"卑尔根机场","name_en":"Bergen Flesland","city":"卑尔根","city_en":"Bergen","country":"挪威","country_en":"Norway","lat":60.2934,"lon":5.2181},
    "ARN": {"name":"斯德哥尔摩阿兰达机场","name_en":"Stockholm Arlanda","city":"斯德哥尔摩","city_en":"Stockholm","country":"瑞典","country_en":"Sweden","lat":59.6519,"lon":17.9186},
    "GOT": {"name":"哥德堡机场","name_en":"Gothenburg Landvetter","city":"哥德堡","city_en":"Gothenburg","country":"瑞典","country_en":"Sweden","lat":57.6628,"lon":12.2798},
    "HEL": {"name":"赫尔辛基万塔机场","name_en":"Helsinki Vantaa","city":"赫尔辛基","city_en":"Helsinki","country":"芬兰","country_en":"Finland","lat":60.3172,"lon":24.9633},
    "KEF": {"name":"雷克雅未克凯夫拉维克机场","name_en":"Reykjavik Keflavik","city":"雷克雅未克","city_en":"Reykjavik","country":"冰岛","country_en":"Iceland","lat":63.985,"lon":-22.6056},
    "DUB": {"name":"都柏林机场","name_en":"Dublin Airport","city":"都柏林","city_en":"Dublin","country":"爱尔兰","country_en":"Ireland","lat":53.4264,"lon":-6.2499},
    "SNN": {"name":"香农机场","name_en":"Shannon Airport","city":"香农","city_en":"Shannon","country":"爱尔兰","country_en":"Ireland","lat":52.7019,"lon":-8.9248},
    "WAW": {"name":"华沙肖邦机场","name_en":"Warsaw Chopin","city":"华沙","city_en":"Warsaw","country":"波兰","country_en":"Poland","lat":52.1657,"lon":20.9671},
    "KRK": {"name":"克拉科夫机场","name_en":"Kraków John Paul II","city":"克拉科夫","city_en":"Kraków","country":"波兰","country_en":"Poland","lat":50.0777,"lon":19.7848},
    "PRG": {"name":"布拉格机场","name_en":"Prague Václav Havel","city":"布拉格","city_en":"Prague","country":"捷克","country_en":"Czech Republic","lat":50.1008,"lon":14.26},
    "BUD": {"name":"布达佩斯机场","name_en":"Budapest Ferenc Liszt","city":"布达佩斯","city_en":"Budapest","country":"匈牙利","country_en":"Hungary","lat":47.4298,"lon":19.2611},
    "OTP": {"name":"布加勒斯特机场","name_en":"Bucharest Henri Coanda","city":"布加勒斯特","city_en":"Bucharest","country":"罗马尼亚","country_en":"Romania","lat":44.5711,"lon":26.085},
    "SOF": {"name":"索非亚机场","name_en":"Sofia Airport","city":"索非亚","city_en":"Sofia","country":"保加利亚","country_en":"Bulgaria","lat":42.6952,"lon":23.4114},
    "BEG": {"name":"贝尔格莱德机场","name_en":"Belgrade Nikola Tesla","city":"贝尔格莱德","city_en":"Belgrade","country":"塞尔维亚","country_en":"Serbia","lat":44.8184,"lon":20.3091},
    "ZAG": {"name":"萨格勒布机场","name_en":"Zagreb Franjo Tudman","city":"萨格勒布","city_en":"Zagreb","country":"克罗地亚","country_en":"Croatia","lat":45.7429,"lon":16.0688},
    "DBV": {"name":"杜布罗夫尼克机场","name_en":"Dubrovnik Airport","city":"杜布罗夫尼克","city_en":"Dubrovnik","country":"克罗地亚","country_en":"Croatia","lat":42.5614,"lon":18.2682},
    "LJU": {"name":"卢布尔雅那机场","name_en":"Ljubljana Jože Pučnik","city":"卢布尔雅那","city_en":"Ljubljana","country":"斯洛文尼亚","country_en":"Slovenia","lat":46.2237,"lon":14.4576},
    "TIA": {"name":"地拉那机场","name_en":"Tirana Intl Nënë Tereza","city":"地拉那","city_en":"Tirana","country":"阿尔巴尼亚","country_en":"Albania","lat":41.4147,"lon":19.7206},
    "SKP": {"name":"斯科普里机场","name_en":"Skopje Alexander the Great","city":"斯科普里","city_en":"Skopje","country":"北马其顿","country_en":"North Macedonia","lat":41.9616,"lon":21.6214},
    "TLL": {"name":"塔林机场","name_en":"Tallinn Lennart Meri","city":"塔林","city_en":"Tallinn","country":"爱沙尼亚","country_en":"Estonia","lat":59.4133,"lon":24.8328},
    "RIX": {"name":"里加机场","name_en":"Riga Intl","city":"里加","city_en":"Riga","country":"拉脱维亚","country_en":"Latvia","lat":56.9236,"lon":23.9711},
    "VNO": {"name":"维尔纽斯机场","name_en":"Vilnius Airport","city":"维尔纽斯","city_en":"Vilnius","country":"立陶宛","country_en":"Lithuania","lat":54.6341,"lon":25.2858},
    "SVO": {"name":"莫斯科谢列梅捷沃机场","name_en":"Moscow Sheremetyevo","city":"莫斯科","city_en":"Moscow","country":"俄罗斯","country_en":"Russia","lat":55.9726,"lon":37.4146},
    "DME": {"name":"莫斯科多莫杰多沃机场","name_en":"Moscow Domodedovo","city":"莫斯科","city_en":"Moscow","country":"俄罗斯","country_en":"Russia","lat":55.4088,"lon":37.9063},
    "VKO": {"name":"莫斯科伏努科沃机场","name_en":"Moscow Vnukovo","city":"莫斯科","city_en":"Moscow","country":"俄罗斯","country_en":"Russia","lat":55.5915,"lon":37.2615},
    "LED": {"name":"圣彼得堡普尔科沃机场","name_en":"St Petersburg Pulkovo","city":"圣彼得堡","city_en":"St Petersburg","country":"俄罗斯","country_en":"Russia","lat":59.8003,"lon":30.2625},
    # ======== 北美洲 ========
    "JFK": {"name":"纽约肯尼迪机场","name_en":"New York JFK","city":"纽约","city_en":"New York","country":"美国","country_en":"United States","lat":40.6413,"lon":-73.7781},
    "EWR": {"name":"纽瓦克自由机场","name_en":"Newark Liberty Intl","city":"纽约","city_en":"New York","country":"美国","country_en":"United States","lat":40.6895,"lon":-74.1745},
    "LGA": {"name":"纽约拉瓜迪亚机场","name_en":"New York LaGuardia","city":"纽约","city_en":"New York","country":"美国","country_en":"United States","lat":40.7769,"lon":-73.8740},
    "LAX": {"name":"洛杉矶国际机场","name_en":"Los Angeles Intl","city":"洛杉矶","city_en":"Los Angeles","country":"美国","country_en":"United States","lat":33.9416,"lon":-118.4085},
    "SFO": {"name":"旧金山国际机场","name_en":"San Francisco Intl","city":"旧金山","city_en":"San Francisco","country":"美国","country_en":"United States","lat":37.6213,"lon":-122.379},
    "ORD": {"name":"芝加哥奥黑尔机场","name_en":"Chicago O'Hare Intl","city":"芝加哥","city_en":"Chicago","country":"美国","country_en":"United States","lat":41.9742,"lon":-87.9073},
    "ATL": {"name":"亚特兰大机场","name_en":"Atlanta Hartsfield-Jackson","city":"亚特兰大","city_en":"Atlanta","country":"美国","country_en":"United States","lat":33.6407,"lon":-84.4277},
    "DFW": {"name":"达拉斯/沃斯堡机场","name_en":"Dallas/Fort Worth Intl","city":"达拉斯","city_en":"Dallas","country":"美国","country_en":"United States","lat":32.8998,"lon":-97.0403},
    "DEN": {"name":"丹佛国际机场","name_en":"Denver Intl","city":"丹佛","city_en":"Denver","country":"美国","country_en":"United States","lat":39.8561,"lon":-104.6737},
    "SEA": {"name":"西雅图-塔科马机场","name_en":"Seattle-Tacoma Intl","city":"西雅图","city_en":"Seattle","country":"美国","country_en":"United States","lat":47.4502,"lon":-122.3088},
    "MIA": {"name":"迈阿密国际机场","name_en":"Miami Intl","city":"迈阿密","city_en":"Miami","country":"美国","country_en":"United States","lat":25.7959,"lon":-80.287},
    "IAD": {"name":"华盛顿杜勒斯机场","name_en":"Washington Dulles Intl","city":"华盛顿","city_en":"Washington","country":"美国","country_en":"United States","lat":38.9531,"lon":-77.4565},
    "DCA": {"name":"华盛顿里根机场","name_en":"Washington Reagan Natl","city":"华盛顿","city_en":"Washington","country":"美国","country_en":"United States","lat":38.8512,"lon":-77.0402},
    "BOS": {"name":"波士顿洛根机场","name_en":"Boston Logan Intl","city":"波士顿","city_en":"Boston","country":"美国","country_en":"United States","lat":42.3656,"lon":-71.0096},
    "IAH": {"name":"休斯顿乔治布什机场","name_en":"Houston George Bush Intercont","city":"休斯顿","city_en":"Houston","country":"美国","country_en":"United States","lat":29.9844,"lon":-95.3414},
    "PHX": {"name":"凤凰城天港机场","name_en":"Phoenix Sky Harbor Intl","city":"凤凰城","city_en":"Phoenix","country":"美国","country_en":"United States","lat":33.4373,"lon":-112.0078},
    "MSP": {"name":"明尼阿波利斯-圣保罗机场","name_en":"Minneapolis-St Paul Intl","city":"明尼阿波利斯","city_en":"Minneapolis","country":"美国","country_en":"United States","lat":44.8848,"lon":-93.2223},
    "DTW": {"name":"底特律都会韦恩县机场","name_en":"Detroit Metropolitan Wayne County","city":"底特律","city_en":"Detroit","country":"美国","country_en":"United States","lat":42.2124,"lon":-83.3534},
    "MCO": {"name":"奥兰多国际机场","name_en":"Orlando Intl","city":"奥兰多","city_en":"Orlando","country":"美国","country_en":"United States","lat":28.4312,"lon":-81.3081},
    "FLL": {"name":"劳德代尔堡机场","name_en":"Fort Lauderdale-Hollywood Intl","city":"劳德代尔堡","city_en":"Fort Lauderdale","country":"美国","country_en":"United States","lat":26.0726,"lon":-80.1527},
    "PHL": {"name":"费城国际机场","name_en":"Philadelphia Intl","city":"费城","city_en":"Philadelphia","country":"美国","country_en":"United States","lat":39.8721,"lon":-75.2411},
    "CLT": {"name":"夏洛特道格拉斯机场","name_en":"Charlotte Douglas Intl","city":"夏洛特","city_en":"Charlotte","country":"美国","country_en":"United States","lat":35.2140,"lon":-80.9431},
    "SAN": {"name":"圣迭戈国际机场","name_en":"San Diego Intl","city":"圣迭戈","city_en":"San Diego","country":"美国","country_en":"United States","lat":32.7336,"lon":-117.1897},
    "SLC": {"name":"盐湖城国际机场","name_en":"Salt Lake City Intl","city":"盐湖城","city_en":"Salt Lake City","country":"美国","country_en":"United States","lat":40.7884,"lon":-111.9778},
    "PDX": {"name":"波特兰国际机场","name_en":"Portland Intl","city":"波特兰","city_en":"Portland","country":"美国","country_en":"United States","lat":45.5898,"lon":-122.5951},
    "TPA": {"name":"坦帕国际机场","name_en":"Tampa Intl","city":"坦帕","city_en":"Tampa","country":"美国","country_en":"United States","lat":27.9755,"lon":-82.5332},
    "LAS": {"name":"拉斯维加斯麦卡伦机场","name_en":"Las Vegas Harry Reid Intl","city":"拉斯维加斯","city_en":"Las Vegas","country":"美国","country_en":"United States","lat":36.0840,"lon":-115.1537},
    "HNL": {"name":"檀香山机场","name_en":"Honolulu Daniel K. Inouye Intl","city":"檀香山","city_en":"Honolulu","country":"美国","country_en":"United States","lat":21.3187,"lon":-157.9225},
    "ANC": {"name":"安克雷奇机场","name_en":"Anchorage Ted Stevens","city":"安克雷奇","city_en":"Anchorage","country":"美国","country_en":"United States","lat":61.1741,"lon":-149.9982},
    "YVR": {"name":"温哥华国际机场","name_en":"Vancouver Intl","city":"温哥华","city_en":"Vancouver","country":"加拿大","country_en":"Canada","lat":49.1967,"lon":-123.1815},
    "YYZ": {"name":"多伦多皮尔逊机场","name_en":"Toronto Pearson Intl","city":"多伦多","city_en":"Toronto","country":"加拿大","country_en":"Canada","lat":43.6777,"lon":-79.6248},
    "YUL": {"name":"蒙特利尔特鲁多机场","name_en":"Montréal Trudeau Intl","city":"蒙特利尔","city_en":"Montréal","country":"加拿大","country_en":"Canada","lat":45.4706,"lon":-73.7408},
    "YOW": {"name":"渥太华机场","name_en":"Ottawa Macdonald-Cartier","city":"渥太华","city_en":"Ottawa","country":"加拿大","country_en":"Canada","lat":45.3225,"lon":-75.6692},
    "YYC": {"name":"卡尔加里机场","name_en":"Calgary Intl","city":"卡尔加里","city_en":"Calgary","country":"加拿大","country_en":"Canada","lat":51.1215,"lon":-114.0076},
    "YEG": {"name":"埃德蒙顿机场","name_en":"Edmonton Intl","city":"埃德蒙顿","city_en":"Edmonton","country":"加拿大","country_en":"Canada","lat":53.3097,"lon":-113.5797},
    "YWG": {"name":"温尼伯机场","name_en":"Winnipeg James Armstrong Richardson","city":"温尼伯","city_en":"Winnipeg","country":"加拿大","country_en":"Canada","lat":49.9100,"lon":-97.2398},
    "YHZ": {"name":"哈利法克斯机场","name_en":"Halifax Stanfield Intl","city":"哈利法克斯","city_en":"Halifax","country":"加拿大","country_en":"Canada","lat":44.8808,"lon":-63.5086},
    "MEX": {"name":"墨西哥城贝尼托华雷斯机场","name_en":"Mexico City Benito Juárez","city":"墨西哥城","city_en":"Mexico City","country":"墨西哥","country_en":"Mexico","lat":19.4363,"lon":-99.0721},
    "CUN": {"name":"坎昆国际机场","name_en":"Cancún Intl","city":"坎昆","city_en":"Cancún","country":"墨西哥","country_en":"Mexico","lat":21.0365,"lon":-86.877},
    "GDL": {"name":"瓜达拉哈拉机场","name_en":"Guadalajara Miguel Hidalgo","city":"瓜达拉哈拉","city_en":"Guadalajara","country":"墨西哥","country_en":"Mexico","lat":20.5218,"lon":-103.3112},
    "SJO": {"name":"圣何塞胡安圣塔玛丽亚机场","name_en":"San José Juan Santamaría","city":"圣何塞","city_en":"San José","country":"哥斯达黎加","country_en":"Costa Rica","lat":9.9939,"lon":-84.2088},
    "PTY": {"name":"巴拿马城托库门机场","name_en":"Panama City Tocumen Intl","city":"巴拿马城","city_en":"Panama City","country":"巴拿马","country_en":"Panama","lat":9.0714,"lon":-79.3835},
    "HAV": {"name":"哈瓦那何塞马蒂机场","name_en":"Havana José Martí Intl","city":"哈瓦那","city_en":"Havana","country":"古巴","country_en":"Cuba","lat":22.9892,"lon":-82.4091},
    # ======== 南美洲 ========
    "GRU": {"name":"圣保罗瓜鲁柳斯机场","name_en":"São Paulo Guarulhos","city":"圣保罗","city_en":"São Paulo","country":"巴西","country_en":"Brazil","lat":-23.4356,"lon":-46.4731},
    "GIG": {"name":"里约热内卢加利昂机场","name_en":"Rio de Janeiro Galeão","city":"里约热内卢","city_en":"Rio de Janeiro","country":"巴西","country_en":"Brazil","lat":-22.8100,"lon":-43.2505},
    "BSB": {"name":"巴西利亚机场","name_en":"Brasília Intl","city":"巴西利亚","city_en":"Brasília","country":"巴西","country_en":"Brazil","lat":-15.8711,"lon":-47.9186},
    "EZE": {"name":"布宜诺斯艾利斯埃塞萨机场","name_en":"Buenos Aires Ezeiza","city":"布宜诺斯艾利斯","city_en":"Buenos Aires","country":"阿根廷","country_en":"Argentina","lat":-34.8222,"lon":-58.5358},
    "AEP": {"name":"布宜诺斯艾利斯豪尔赫纽贝里机场","name_en":"Buenos Aires Jorge Newbery","city":"布宜诺斯艾利斯","city_en":"Buenos Aires","country":"阿根廷","country_en":"Argentina","lat":-34.5592,"lon":-58.4156},
    "SCL": {"name":"圣地亚哥阿图罗梅里诺机场","name_en":"Santiago Arturo Merino Benítez","city":"圣地亚哥","city_en":"Santiago","country":"智利","country_en":"Chile","lat":-33.3930,"lon":-70.7858},
    "LIM": {"name":"利马豪尔赫查韦斯机场","name_en":"Lima Jorge Chávez","city":"利马","city_en":"Lima","country":"秘鲁","country_en":"Peru","lat":-12.0219,"lon":-77.1143},
    "BOG": {"name":"波哥大埃尔多拉多机场","name_en":"Bogotá El Dorado","city":"波哥大","city_en":"Bogotá","country":"哥伦比亚","country_en":"Colombia","lat":4.7016,"lon":-74.1469},
    "MDE": {"name":"麦德林何塞马利亚机场","name_en":"Medellín José María Córdova","city":"麦德林","city_en":"Medellín","country":"哥伦比亚","country_en":"Colombia","lat":6.1645,"lon":-75.4231},
    "UIO": {"name":"基多马里斯卡尔苏克雷机场","name_en":"Quito Mariscal Sucre","city":"基多","city_en":"Quito","country":"厄瓜多尔","country_en":"Ecuador","lat":-0.1292,"lon":-78.3575},
    "CCS": {"name":"加拉加斯西蒙玻利瓦尔机场","name_en":"Caracas Simón Bolívar","city":"加拉加斯","city_en":"Caracas","country":"委内瑞拉","country_en":"Venezuela","lat":10.6012,"lon":-66.9913},
    "MVD": {"name":"蒙得维的亚卡拉斯科机场","name_en":"Montevideo Carrasco Intl","city":"蒙得维的亚","city_en":"Montevideo","country":"乌拉圭","country_en":"Uruguay","lat":-34.8384,"lon":-56.0308},
    "ASU": {"name":"亚松森机场","name_en":"Asunción Silvio Pettirossi","city":"亚松森","city_en":"Asunción","country":"巴拉圭","country_en":"Paraguay","lat":-25.2400,"lon":-57.5200},
    "VVI": {"name":"圣克鲁斯维鲁维鲁机场","name_en":"Santa Cruz Viru Viru","city":"圣克鲁斯","city_en":"Santa Cruz","country":"玻利维亚","country_en":"Bolivia","lat":-17.6448,"lon":-63.1354},
    # ======== 非洲 ========
    "JNB": {"name":"约翰内斯堡奥利弗坦博机场","name_en":"Johannesburg O.R. Tambo","city":"约翰内斯堡","city_en":"Johannesburg","country":"南非","country_en":"South Africa","lat":-26.1392,"lon":28.246},
    "CPT": {"name":"开普敦国际机场","name_en":"Cape Town Intl","city":"开普敦","city_en":"Cape Town","country":"南非","country_en":"South Africa","lat":-33.9649,"lon":18.6017},
    "DUR": {"name":"德班沙卡国王机场","name_en":"Durban King Shaka Intl","city":"德班","city_en":"Durban","country":"南非","country_en":"South Africa","lat":-29.6144,"lon":31.1197},
    "CAI": {"name":"开罗国际机场","name_en":"Cairo Intl","city":"开罗","city_en":"Cairo","country":"埃及","country_en":"Egypt","lat":30.1219,"lon":31.4056},
    "SSH": {"name":"沙姆沙伊赫机场","name_en":"Sharm El Sheikh Intl","city":"沙姆沙伊赫","city_en":"Sharm El Sheikh","country":"埃及","country_en":"Egypt","lat":27.9773,"lon":34.3950},
    "HRG": {"name":"赫尔格达机场","name_en":"Hurghada Intl","city":"赫尔格达","city_en":"Hurghada","country":"埃及","country_en":"Egypt","lat":27.1784,"lon":33.7994},
    "CMN": {"name":"卡萨布兰卡穆罕默德五世机场","name_en":"Casablanca Mohammed V","city":"卡萨布兰卡","city_en":"Casablanca","country":"摩洛哥","country_en":"Morocco","lat":33.3675,"lon":-7.5898},
    "RAK": {"name":"马拉喀什机场","name_en":"Marrakech Menara","city":"马拉喀什","city_en":"Marrakech","country":"摩洛哥","country_en":"Morocco","lat":31.6069,"lon":-8.0363},
    "TUN": {"name":"突尼斯迦太基机场","name_en":"Tunis Carthage","city":"突尼斯","city_en":"Tunis","country":"突尼斯","country_en":"Tunisia","lat":36.8510,"lon":10.2272},
    "ALG": {"name":"阿尔及尔机场","name_en":"Algiers Houari Boumediene","city":"阿尔及尔","city_en":"Algiers","country":"阿尔及利亚","country_en":"Algeria","lat":36.6910,"lon":3.2154},
    "NBO": {"name":"内罗毕肯雅塔机场","name_en":"Nairobi Jomo Kenyatta","city":"内罗毕","city_en":"Nairobi","country":"肯尼亚","country_en":"Kenya","lat":-1.3192,"lon":36.9278},
    "ADD": {"name":"亚的斯亚贝巴博莱机场","name_en":"Addis Ababa Bole","city":"亚的斯亚贝巴","city_en":"Addis Ababa","country":"埃塞俄比亚","country_en":"Ethiopia","lat":8.9779,"lon":38.7992},
    "LOS": {"name":"拉各斯穆尔塔拉穆罕默德机场","name_en":"Lagos Murtala Muhammed","city":"拉各斯","city_en":"Lagos","country":"尼日利亚","country_en":"Nigeria","lat":6.5774,"lon":3.3212},
    "ABJ": {"name":"阿比让机场","name_en":"Abidjan Félix-Houphouët-Boigny","city":"阿比让","city_en":"Abidjan","country":"科特迪瓦","country_en":"Ivory Coast","lat":5.2614,"lon":-3.9262},
    "ACC": {"name":"阿克拉科托卡机场","name_en":"Accra Kotoka Intl","city":"阿克拉","city_en":"Accra","country":"加纳","country_en":"Ghana","lat":5.6052,"lon":-0.1668},
    "DSS": {"name":"达喀尔布莱兹迪亚涅机场","name_en":"Dakar Blaise Diagne","city":"达喀尔","city_en":"Dakar","country":"塞内加尔","country_en":"Senegal","lat":14.6700,"lon":-17.0733},
    "DAR": {"name":"达累斯萨拉姆朱利叶斯尼雷尔机场","name_en":"Dar es Salaam Julius Nyerere","city":"达累斯萨拉姆","city_en":"Dar es Salaam","country":"坦桑尼亚","country_en":"Tanzania","lat":-6.8781,"lon":39.2026},
    "EBB": {"name":"坎帕拉恩德培机场","name_en":"Kampala Entebbe Intl","city":"坎帕拉","city_en":"Kampala","country":"乌干达","country_en":"Uganda","lat":0.0424,"lon":32.4435},
    "KGL": {"name":"基加利机场","name_en":"Kigali Intl","city":"基加利","city_en":"Kigali","country":"卢旺达","country_en":"Rwanda","lat":-1.9686,"lon":30.1395},
    "MRU": {"name":"毛里求斯机场","name_en":"Mauritius Sir Seewoosagur Ramgoolam","city":"路易港","city_en":"Port Louis","country":"毛里求斯","country_en":"Mauritius","lat":-20.4302,"lon":57.6836},
    "SEZ": {"name":"塞舌尔国际机场","name_en":"Seychelles Intl","city":"维多利亚","city_en":"Victoria","country":"塞舌尔","country_en":"Seychelles","lat":-4.6743,"lon":55.5219},
    "TNR": {"name":"塔那那利佛机场","name_en":"Antananarivo Ivato","city":"塔那那利佛","city_en":"Antananarivo","country":"马达加斯加","country_en":"Madagascar","lat":-18.7969,"lon":47.4789},
    # ======== 大洋洲 ========
    "SYD": {"name":"悉尼金斯福德史密斯机场","name_en":"Sydney Kingsford Smith","city":"悉尼","city_en":"Sydney","country":"澳大利亚","country_en":"Australia","lat":-33.9461,"lon":151.1772},
    "MEL": {"name":"墨尔本塔拉马林机场","name_en":"Melbourne Tullamarine","city":"墨尔本","city_en":"Melbourne","country":"澳大利亚","country_en":"Australia","lat":-37.6733,"lon":144.8433},
    "BNE": {"name":"布里斯班机场","name_en":"Brisbane Airport","city":"布里斯班","city_en":"Brisbane","country":"澳大利亚","country_en":"Australia","lat":-27.3842,"lon":153.1175},
    "PER": {"name":"珀斯机场","name_en":"Perth Airport","city":"珀斯","city_en":"Perth","country":"澳大利亚","country_en":"Australia","lat":-31.9403,"lon":115.9672},
    "ADL": {"name":"阿德莱德机场","name_en":"Adelaide Airport","city":"阿德莱德","city_en":"Adelaide","country":"澳大利亚","country_en":"Australia","lat":-34.9450,"lon":138.5306},
    "CNS": {"name":"凯恩斯机场","name_en":"Cairns Airport","city":"凯恩斯","city_en":"Cairns","country":"澳大利亚","country_en":"Australia","lat":-16.8858,"lon":145.7554},
    "OOL": {"name":"黄金海岸机场","name_en":"Gold Coast Airport","city":"黄金海岸","city_en":"Gold Coast","country":"澳大利亚","country_en":"Australia","lat":-28.1644,"lon":153.5047},
    "CBR": {"name":"堪培拉机场","name_en":"Canberra Airport","city":"堪培拉","city_en":"Canberra","country":"澳大利亚","country_en":"Australia","lat":-35.3069,"lon":149.1950},
    "DRW": {"name":"达尔文机场","name_en":"Darwin Intl","city":"达尔文","city_en":"Darwin","country":"澳大利亚","country_en":"Australia","lat":-12.4147,"lon":130.8769},
    "HBA": {"name":"霍巴特机场","name_en":"Hobart Intl","city":"霍巴特","city_en":"Hobart","country":"澳大利亚","country_en":"Australia","lat":-42.8361,"lon":147.5103},
    "AKL": {"name":"奥克兰机场","name_en":"Auckland Airport","city":"奥克兰","city_en":"Auckland","country":"新西兰","country_en":"New Zealand","lat":-37.0082,"lon":174.7850},
    "WLG": {"name":"惠灵顿机场","name_en":"Wellington Airport","city":"惠灵顿","city_en":"Wellington","country":"新西兰","country_en":"New Zealand","lat":-41.3272,"lon":174.8053},
    "CHC": {"name":"基督城机场","name_en":"Christchurch Intl","city":"基督城","city_en":"Christchurch","country":"新西兰","country_en":"New Zealand","lat":-43.4894,"lon":172.5322},
    "ZQN": {"name":"皇后镇机场","name_en":"Queenstown Airport","city":"皇后镇","city_en":"Queenstown","country":"新西兰","country_en":"New Zealand","lat":-45.0211,"lon":168.7392},
    "NAN": {"name":"楠迪国际机场","name_en":"Nadi Intl","city":"楠迪","city_en":"Nadi","country":"斐济","country_en":"Fiji","lat":-17.7553,"lon":177.4431},
    "PPT": {"name":"帕皮提法阿机场","name_en":"Papeete Faa'a Intl","city":"帕皮提","city_en":"Papeete","country":"法属波利尼西亚","country_en":"French Polynesia","lat":-17.5537,"lon":-149.6097},
    "GUM": {"name":"关岛国际机场","name_en":"Guam Antonio B. Won Pat Intl","city":"关岛","city_en":"Guam","country":"关岛","country_en":"Guam","lat":13.4834,"lon":144.796},
    "SPN": {"name":"塞班机场","name_en":"Saipan Intl","city":"塞班","city_en":"Saipan","country":"北马里亚纳群岛","country_en":"Northern Mariana Islands","lat":15.119,"lon":145.7294},
    "NOU": {"name":"努美阿机场","name_en":"Nouméa La Tontouta","city":"努美阿","city_en":"Nouméa","country":"新喀里多尼亚","country_en":"New Caledonia","lat":-22.0146,"lon":166.2128},
    # ======== 中亚/高加索 ========
    "NQZ": {"name":"努尔苏丹纳扎尔巴耶夫机场","name_en":"Astana Nursultan Nazarbayev","city":"阿斯塔纳","city_en":"Astana","country":"哈萨克斯坦","country_en":"Kazakhstan","lat":51.0222,"lon":71.4669},
    "ALA": {"name":"阿拉木图机场","name_en":"Almaty Intl","city":"阿拉木图","city_en":"Almaty","country":"哈萨克斯坦","country_en":"Kazakhstan","lat":43.3521,"lon":77.0405},
    "TAS": {"name":"塔什干机场","name_en":"Tashkent Islam Karimov","city":"塔什干","city_en":"Tashkent","country":"乌兹别克斯坦","country_en":"Uzbekistan","lat":41.2579,"lon":69.2812},
    "TBS": {"name":"第比利斯机场","name_en":"Tbilisi Shota Rustaveli","city":"第比利斯","city_en":"Tbilisi","country":"格鲁吉亚","country_en":"Georgia","lat":41.6692,"lon":44.9547},
    "GYD": {"name":"巴库盖达尔阿利耶夫机场","name_en":"Baku Heydar Aliyev","city":"巴库","city_en":"Baku","country":"阿塞拜疆","country_en":"Azerbaijan","lat":40.4675,"lon":50.0467},
    "EVN": {"name":"埃里温兹瓦尔特诺茨机场","name_en":"Yerevan Zvartnots","city":"埃里温","city_en":"Yerevan","country":"亚美尼亚","country_en":"Armenia","lat":40.1473,"lon":44.3959},
    "ULN": {"name":"乌兰巴托成吉思汗机场","name_en":"Ulaanbaatar Chinggis Khaan","city":"乌兰巴托","city_en":"Ulaanbaatar","country":"蒙古","country_en":"Mongolia","lat":47.8431,"lon":106.7667},
}

# =====================================================================
# 全球航空公司数据库 — 约 400+ 航空公司
# 格式: IATA -> {name, name_en, country}
# =====================================================================
AIRLINES = {
    # ======== 中国大陆 ========
    "CA": {"name":"中国国航","name_en":"Air China","country":"中国"},
    "MU": {"name":"东方航空","name_en":"China Eastern Airlines","country":"中国"},
    "CZ": {"name":"南方航空","name_en":"China Southern Airlines","country":"中国"},
    "HU": {"name":"海南航空","name_en":"Hainan Airlines","country":"中国"},
    "ZH": {"name":"深圳航空","name_en":"Shenzhen Airlines","country":"中国"},
    "MF": {"name":"厦门航空","name_en":"Xiamen Airlines","country":"中国"},
    "FM": {"name":"上海航空","name_en":"Shanghai Airlines","country":"中国"},
    "SC": {"name":"山东航空","name_en":"Shandong Airlines","country":"中国"},
    "3U": {"name":"四川航空","name_en":"Sichuan Airlines","country":"中国"},
    "GS": {"name":"天津航空","name_en":"Tianjin Airlines","country":"中国"},
    "KN": {"name":"联合航空","name_en":"China United Airlines","country":"中国"},
    "9C": {"name":"春秋航空","name_en":"Spring Airlines","country":"中国"},
    "G5": {"name":"华夏航空","name_en":"China Express Airlines","country":"中国"},
    "TV": {"name":"西藏航空","name_en":"Tibet Airlines","country":"中国"},
    "PN": {"name":"西部航空","name_en":"West Air","country":"中国"},
    "EU": {"name":"成都航空","name_en":"Chengdu Airlines","country":"中国"},
    "KY": {"name":"昆明航空","name_en":"Kunming Airlines","country":"中国"},
    "JD": {"name":"首都航空","name_en":"Capital Airlines","country":"中国"},
    "DZ": {"name":"东海航空","name_en":"Donghai Airlines","country":"中国"},
    "GJ": {"name":"长龙航空","name_en":"Loong Air","country":"中国"},
    "QW": {"name":"青岛航空","name_en":"Qingdao Airlines","country":"中国"},
    "CN": {"name":"大新华航空","name_en":"Grand China Air","country":"中国"},
    "8L": {"name":"祥鹏航空","name_en":"Lucky Air","country":"中国"},
    "GT": {"name":"桂林航空","name_en":"Guilin Airlines","country":"中国"},
    "Y8": {"name":"扬子江航空","name_en":"Yangtze River Airlines","country":"中国"},
    "NS": {"name":"河北航空","name_en":"Hebei Airlines","country":"中国"},
    "BK": {"name":"奥凯航空","name_en":"Okay Airways","country":"中国"},
    "UQ": {"name":"乌鲁木齐航空","name_en":"Urumqi Air","country":"中国"},
    "AQ": {"name":"九元航空","name_en":"9 Air","country":"中国"},
    "HO": {"name":"吉祥航空","name_en":"Juneyao Airlines","country":"中国"},
    "GX": {"name":"广西北部湾航空","name_en":"GX Airlines","country":"中国"},
    "DR": {"name":"瑞丽航空","name_en":"Ruili Airlines","country":"中国"},
    "RY": {"name":"江西航空","name_en":"Jiangxi Air","country":"中国"},
    "JR": {"name":"幸福航空","name_en":"Joy Air","country":"中国"},
    "GY": {"name":"多彩贵州航空","name_en":"Colorful Guizhou Airlines","country":"中国"},
    "QD": {"name":"海航旗下航司","name_en":"HNA Group","country":"中国"},
    "FU": {"name":"福州航空","name_en":"Fuzhou Airlines","country":"中国"},
    "A6": {"name":"天骄航空","name_en":"Air Travel","country":"中国"},
    "2Z": {"name":"东北航空","name_en":"Dongbei Airlines","country":"中国"},
    # ======== 港澳台 ========
    "CX": {"name":"国泰航空","name_en":"Cathay Pacific","country":"中国"},
    "KA": {"name":"港龙航空","name_en":"Cathay Dragon","country":"中国"},
    "HX": {"name":"香港航空","name_en":"Hong Kong Airlines","country":"中国"},
    "UO": {"name":"香港快运","name_en":"HK Express","country":"中国"},
    "NX": {"name":"澳门航空","name_en":"Air Macau","country":"中国"},
    "BR": {"name":"长荣航空","name_en":"EVA Air","country":"中国"},
    "CI": {"name":"中华航空","name_en":"China Airlines","country":"中国"},
    "IT": {"name":"台湾虎航","name_en":"Tigerair Taiwan","country":"中国"},
    "BX": {"name":"立荣航空","name_en":"Uni Air","country":"中国"},
    "AE": {"name":"华信航空","name_en":"Mandarin Airlines","country":"中国"},
    "B7": {"name":"立荣航空","name_en":"Uni Air","country":"中国"},
    # ======== 日本 ========
    "NH": {"name":"全日空","name_en":"All Nippon Airways","country":"日本"},
    "JL": {"name":"日本航空","name_en":"Japan Airlines","country":"日本"},
    "BC": {"name":"天马航空","name_en":"Skymark Airlines","country":"日本"},
    "MM": {"name":"乐桃航空","name_en":"Peach Aviation","country":"日本"},
    "GK": {"name":"捷星日本","name_en":"Jetstar Japan","country":"日本"},
    "JW": {"name":"香草航空","name_en":"Vanilla Air","country":"日本"},
    "HD": {"name":"北海道国际航空","name_en":"AIRDO","country":"日本"},
    "SJ": {"name":"Solaseed Air","name_en":"Solaseed Air","country":"日本"},
    "7G": {"name":"星悦航空","name_en":"StarFlyer","country":"日本"},
    "NU": {"name":"日本越洋航空","name_en":"Japan Transocean Air","country":"日本"},
    "IJ": {"name":"春秋航空日本","name_en":"Spring Airlines Japan","country":"日本"},
    "DJ": {"name":"ZIP AIR","name_en":"ZIPAIR Tokyo","country":"日本"},
    # ======== 韩国 ========
    "KE": {"name":"大韩航空","name_en":"Korean Air","country":"韩国"},
    "OZ": {"name":"韩亚航空","name_en":"Asiana Airlines","country":"韩国"},
    "LJ": {"name":"真航空","name_en":"Jin Air","country":"韩国"},
    "ZE": {"name":"易斯达航空","name_en":"Eastar Jet","country":"韩国"},
    "TW": {"name":"德威航空","name_en":"T'way Air","country":"韩国"},
    "7C": {"name":"济州航空","name_en":"Jeju Air","country":"韩国"},
    "BX2":{"name":"釜山航空","name_en":"Air Busan","country":"韩国"},
    "RS": {"name":"首尔航空","name_en":"Air Seoul","country":"韩国"},
    "4V": {"name":"飞蛙航空","name_en":"Fly Gangwon","country":"韩国"},
    # ======== 东南亚 ========
    "SQ": {"name":"新加坡航空","name_en":"Singapore Airlines","country":"新加坡"},
    "TR": {"name":"酷航","name_en":"Scoot","country":"新加坡"},
    "MI": {"name":"胜安航空","name_en":"SilkAir","country":"新加坡"},
    "TG": {"name":"泰国国际航空","name_en":"Thai Airways","country":"泰国"},
    "FD": {"name":"泰国亚洲航空","name_en":"Thai AirAsia","country":"泰国"},
    "WE": {"name":"泰国微笑航空","name_en":"Thai Smile","country":"泰国"},
    "DD": {"name":"鸟航","name_en":"Nok Air","country":"泰国"},
    "SL": {"name":"泰国狮航","name_en":"Thai Lion Air","country":"泰国"},
    "VZ": {"name":"泰国越捷","name_en":"Thai VietJet Air","country":"泰国"},
    "MH": {"name":"马来西亚航空","name_en":"Malaysia Airlines","country":"马来西亚"},
    "AK": {"name":"亚洲航空","name_en":"AirAsia","country":"马来西亚"},
    "D7": {"name":"亚洲航空X","name_en":"AirAsia X","country":"马来西亚"},
    "OD": {"name":"马印航空","name_en":"Batik Air Malaysia","country":"马来西亚"},
    "VN": {"name":"越南航空","name_en":"Vietnam Airlines","country":"越南"},
    "VJ": {"name":"越捷航空","name_en":"VietJet Air","country":"越南"},
    "BL": {"name":"越竹航空","name_en":"Bamboo Airways","country":"越南"},
    "GA": {"name":"印尼鹰航","name_en":"Garuda Indonesia","country":"印度尼西亚"},
    "ID": {"name":"巴泽航空","name_en":"Batik Air","country":"印度尼西亚"},
    "JT": {"name":"狮子航空","name_en":"Lion Air","country":"印度尼西亚"},
    "QZ": {"name":"亚航印尼","name_en":"Indonesia AirAsia","country":"印度尼西亚"},
    "QG": {"name":"城市连接航空","name_en":"Citilink","country":"印度尼西亚"},
    "PR": {"name":"菲律宾航空","name_en":"Philippine Airlines","country":"菲律宾"},
    "5J": {"name":"宿务太平洋","name_en":"Cebu Pacific","country":"菲律宾"},
    "Z2": {"name":"亚航菲律宾","name_en":"AirAsia Philippines","country":"菲律宾"},
    "K6": {"name":"柬埔寨吴哥航空","name_en":"Cambodia Angkor Air","country":"柬埔寨"},
    "QV": {"name":"老挝航空","name_en":"Lao Airlines","country":"老挝"},
    "8M": {"name":"缅甸国际航空","name_en":"Myanmar Airways International","country":"缅甸"},
    "BI": {"name":"文莱皇家航空","name_en":"Royal Brunei Airlines","country":"文莱"},
    # ======== 南亚 ========
    "AI": {"name":"印度航空","name_en":"Air India","country":"印度"},
    "6E": {"name":"靛蓝航空","name_en":"IndiGo","country":"印度"},
    "UK": {"name":"维斯塔拉航空","name_en":"Vistara","country":"印度"},
    "SG": {"name":"香料航空","name_en":"SpiceJet","country":"印度"},
    "G8": {"name":"走吧航空","name_en":"Go First","country":"印度"},
    "IX": {"name":"印度航空快运","name_en":"Air India Express","country":"印度"},
    "UL": {"name":"斯里兰卡航空","name_en":"SriLankan Airlines","country":"斯里兰卡"},
    "RA": {"name":"尼泊尔航空","name_en":"Nepal Airlines","country":"尼泊尔"},
    "BG": {"name":"比曼航空","name_en":"Biman Bangladesh Airlines","country":"孟加拉"},
    "Q2": {"name":"马尔代夫航空","name_en":"Maldivian","country":"马尔代夫"},
    "PK": {"name":"巴基斯坦航空","name_en":"Pakistan International Airlines","country":"巴基斯坦"},
    # ======== 中东 ========
    "EK": {"name":"阿联酋航空","name_en":"Emirates","country":"阿联酋"},
    "EY": {"name":"阿提哈德航空","name_en":"Etihad Airways","country":"阿联酋"},
    "FZ": {"name":"迪拜航空","name_en":"Flydubai","country":"阿联酋"},
    "G9": {"name":"阿拉伯航空","name_en":"Air Arabia","country":"阿联酋"},
    "QR": {"name":"卡塔尔航空","name_en":"Qatar Airways","country":"卡塔尔"},
    "GF": {"name":"海湾航空","name_en":"Gulf Air","country":"巴林"},
    "WY": {"name":"阿曼航空","name_en":"Oman Air","country":"阿曼"},
    "KU": {"name":"科威特航空","name_en":"Kuwait Airways","country":"科威特"},
    "SV": {"name":"沙特航空","name_en":"Saudia","country":"沙特阿拉伯"},
    "XY": {"name":"flynas","name_en":"flynas","country":"沙特阿拉伯"},
    "TK": {"name":"土耳其航空","name_en":"Turkish Airlines","country":"土耳其"},
    "PC": {"name":"飞马航空","name_en":"Pegasus Airlines","country":"土耳其"},
    "XQ": {"name":"太阳快运","name_en":"SunExpress","country":"土耳其"},
    "LY": {"name":"以色列航空","name_en":"El Al","country":"以色列"},
    "RJ": {"name":"约旦皇家航空","name_en":"Royal Jordanian","country":"约旦"},
    "ME": {"name":"中东航空","name_en":"Middle East Airlines","country":"黎巴嫩"},
    "IR": {"name":"伊朗航空","name_en":"Iran Air","country":"伊朗"},
    "W5": {"name":"马汉航空","name_en":"Mahan Air","country":"伊朗"},
    # ======== 欧洲主要 ========
    "BA": {"name":"英国航空","name_en":"British Airways","country":"英国"},
    "VS": {"name":"维珍大西洋","name_en":"Virgin Atlantic","country":"英国"},
    "U2": {"name":"易捷航空","name_en":"easyJet","country":"英国"},
    "BE": {"name":"Flybe","name_en":"Flybe","country":"英国"},
    "AF": {"name":"法国航空","name_en":"Air France","country":"法国"},
    "TO": {"name":"法国途易飞","name_en":"Transavia France","country":"法国"},
    "LH": {"name":"汉莎航空","name_en":"Lufthansa","country":"德国"},
    "4Y": {"name":"欧洲之翼","name_en":"Eurowings","country":"德国"},
    "DE": {"name":"神鹰航空","name_en":"Condor","country":"德国"},
    "KL": {"name":"荷兰皇家航空","name_en":"KLM Royal Dutch Airlines","country":"荷兰"},
    "HV": {"name":"泛航航空","name_en":"Transavia","country":"荷兰"},
    "SN": {"name":"布鲁塞尔航空","name_en":"Brussels Airlines","country":"比利时"},
    "LX": {"name":"瑞士国际航空","name_en":"Swiss International Air Lines","country":"瑞士"},
    "OS": {"name":"奥地利航空","name_en":"Austrian Airlines","country":"奥地利"},
    "IB": {"name":"伊比利亚航空","name_en":"Iberia","country":"西班牙"},
    "VY": {"name":"伏林航空","name_en":"Vueling","country":"西班牙"},
    "I2": {"name":"Iberia Express","name_en":"Iberia Express","country":"西班牙"},
    "UX": {"name":"欧罗巴航空","name_en":"Air Europa","country":"西班牙"},
    "TP": {"name":"葡萄牙航空","name_en":"TAP Air Portugal","country":"葡萄牙"},
    "AZ": {"name":"ITA航空","name_en":"ITA Airways","country":"意大利"},
    "FR": {"name":"瑞安航空","name_en":"Ryanair","country":"爱尔兰"},
    "EI": {"name":"爱尔兰航空","name_en":"Aer Lingus","country":"爱尔兰"},
    "A3": {"name":"爱琴海航空","name_en":"Aegean Airlines","country":"希腊"},
    "SK": {"name":"北欧航空","name_en":"Scandinavian Airlines","country":"瑞典/丹麦/挪威"},
    "DY": {"name":"挪威航空","name_en":"Norwegian Air Shuttle","country":"挪威"},
    "AY": {"name":"芬兰航空","name_en":"Finnair","country":"芬兰"},
    "FI": {"name":"冰岛航空","name_en":"Icelandair","country":"冰岛"},
    "WW": {"name":"WOW航空","name_en":"WOW Air","country":"冰岛"},
    "LO": {"name":"波兰航空","name_en":"LOT Polish Airlines","country":"波兰"},
    "OK": {"name":"捷克航空","name_en":"Czech Airlines","country":"捷克"},
    "MA": {"name":"匈牙利航空","name_en":"MALÉV","country":"匈牙利"},
    "W6": {"name":"维兹航空","name_en":"Wizz Air","country":"匈牙利"},
    "RO": {"name":"罗马尼亚航空","name_en":"TAROM","country":"罗马尼亚"},
    "FB": {"name":"保加利亚航空","name_en":"Bulgaria Air","country":"保加利亚"},
    "JU": {"name":"塞尔维亚航空","name_en":"Air Serbia","country":"塞尔维亚"},
    "OU": {"name":"克罗地亚航空","name_en":"Croatia Airlines","country":"克罗地亚"},
    "JP": {"name":"亚德里亚航空","name_en":"Adria Airways","country":"斯洛文尼亚"},
    "SU": {"name":"俄罗斯航空","name_en":"Aeroflot","country":"俄罗斯"},
    "S7": {"name":"西伯利亚航空","name_en":"S7 Airlines","country":"俄罗斯"},
    "UT": {"name":"乌塔航空","name_en":"UTair","country":"俄罗斯"},
    "UN": {"name":"全禄航空","name_en":"Transaero","country":"俄罗斯"},
    "BT": {"name":"波罗的海航空","name_en":"airBaltic","country":"拉脱维亚"},
    "OV": {"name":"爱沙尼亚航空","name_en":"Estonian Air","country":"爱沙尼亚"},
    "B2": {"name":"白俄罗斯航空","name_en":"Belavia","country":"白俄罗斯"},
    "PS": {"name":"乌克兰航空","name_en":"Ukraine International Airlines","country":"乌克兰"},
    # ======== 北美 ========
    "AA": {"name":"美国航空","name_en":"American Airlines","country":"美国"},
    "UA": {"name":"美国联合航空","name_en":"United Airlines","country":"美国"},
    "DL": {"name":"达美航空","name_en":"Delta Air Lines","country":"美国"},
    "WN": {"name":"西南航空","name_en":"Southwest Airlines","country":"美国"},
    "B6": {"name":"捷蓝航空","name_en":"JetBlue Airways","country":"美国"},
    "AS": {"name":"阿拉斯加航空","name_en":"Alaska Airlines","country":"美国"},
    "NK": {"name":"精神航空","name_en":"Spirit Airlines","country":"美国"},
    "F9": {"name":"边疆航空","name_en":"Frontier Airlines","country":"美国"},
    "HA": {"name":"夏威夷航空","name_en":"Hawaiian Airlines","country":"美国"},
    "SY": {"name":"太阳城航空","name_en":"Sun Country Airlines","country":"美国"},
    "G4": {"name":"忠实航空","name_en":"Allegiant Air","country":"美国"},
    "AC": {"name":"加拿大航空","name_en":"Air Canada","country":"加拿大"},
    "WS": {"name":"西捷航空","name_en":"WestJet","country":"加拿大"},
    "PD": {"name":"波特航空","name_en":"Porter Airlines","country":"加拿大"},
    "TS": {"name":"越洋航空","name_en":"Air Transat","country":"加拿大"},
    "AM": {"name":"墨西哥航空","name_en":"Aeroméxico","country":"墨西哥"},
    "Y4": {"name":"沃拉里斯","name_en":"Volaris","country":"墨西哥"},
    "4O": {"name":"维瓦航空","name_en":"VivaAerobus","country":"墨西哥"},
    "CM": {"name":"巴拿马航空","name_en":"Copa Airlines","country":"巴拿马"},
    "LR": {"name":"哥斯达黎加航空","name_en":"LACSA","country":"哥斯达黎加"},
    # ======== 南美 ========
    "LA": {"name":"南美航空","name_en":"LATAM Airlines","country":"智利"},
    "JJ": {"name":"巴西天马航空","name_en":"LATAM Brasil","country":"巴西"},
    "G3": {"name":"高尔航空","name_en":"GOL Linhas Aéreas","country":"巴西"},
    "AD": {"name":"阿祖尔航空","name_en":"Azul Brazilian Airlines","country":"巴西"},
    "AR": {"name":"阿根廷航空","name_en":"Aerolíneas Argentinas","country":"阿根廷"},
    "AV": {"name":"哥伦比亚航空","name_en":"Avianca","country":"哥伦比亚"},
    "PZ": {"name":"苏里南TAM","name_en":"LATAM Paraguay","country":"巴拉圭"},
    # ======== 非洲 ========
    "SA": {"name":"南非航空","name_en":"South African Airways","country":"南非"},
    "MS": {"name":"埃及航空","name_en":"EgyptAir","country":"埃及"},
    "ET": {"name":"埃塞俄比亚航空","name_en":"Ethiopian Airlines","country":"埃塞俄比亚"},
    "KQ": {"name":"肯尼亚航空","name_en":"Kenya Airways","country":"肯尼亚"},
    "AT": {"name":"摩洛哥皇家航空","name_en":"Royal Air Maroc","country":"摩洛哥"},
    "WB": {"name":"卢旺达航空","name_en":"RwandAir","country":"卢旺达"},
    "TC": {"name":"坦桑尼亚航空","name_en":"Air Tanzania","country":"坦桑尼亚"},
    "5Z": {"name":"赞比亚航空","name_en":"Zambia Airways","country":"赞比亚"},
    "MK": {"name":"毛里求斯航空","name_en":"Air Mauritius","country":"毛里求斯"},
    "HM": {"name":"塞舌尔航空","name_en":"Air Seychelles","country":"塞舌尔"},
    "MD": {"name":"马达加斯加航空","name_en":"Air Madagascar","country":"马达加斯加"},
    # ======== 大洋洲 ========
    "QF": {"name":"澳洲航空","name_en":"Qantas","country":"澳大利亚"},
    "VA": {"name":"维珍澳洲","name_en":"Virgin Australia","country":"澳大利亚"},
    "JQ": {"name":"捷星航空","name_en":"Jetstar Airways","country":"澳大利亚"},
    "TT": {"name":"虎航澳洲","name_en":"Tigerair Australia","country":"澳大利亚"},
    "NZ": {"name":"新西兰航空","name_en":"Air New Zealand","country":"新西兰"},
    "FJ": {"name":"斐济航空","name_en":"Fiji Airways","country":"斐济"},
    "PX": {"name":"新几内亚航空","name_en":"Air Niugini","country":"巴布亚新几内亚"},
    "SB": {"name":"喀里多尼亚国际航空","name_en":"Aircalin","country":"新喀里多尼亚"},
    # ======== 中亚 ========
    "KC": {"name":"阿斯塔纳航空","name_en":"Air Astana","country":"哈萨克斯坦"},
    "HY": {"name":"乌兹别克航空","name_en":"Uzbekistan Airways","country":"乌兹别克斯坦"},
    "A9": {"name":"格鲁吉亚航空","name_en":"Georgian Airways","country":"格鲁吉亚"},
    "J2": {"name":"阿塞拜疆航空","name_en":"Azerbaijan Airlines","country":"阿塞拜疆"},
    "OM": {"name":"蒙古航空","name_en":"MIAT Mongolian Airlines","country":"蒙古"},
    "IQ": {"name":"伊拉克航空","name_en":"Iraqi Airways","country":"伊拉克"},
    "EP": {"name":"伊朗阿塞曼","name_en":"Iran Aseman Airlines","country":"伊朗"},
    "RB": {"name":"叙利亚航空","name_en":"Syrian Arab Airlines","country":"叙利亚"},
    "5N": {"name":"诺德温航空","name_en":"Nordwind Airlines","country":"俄罗斯"},
}


def main():
    os.makedirs(DATA_DIR, exist_ok=True)

    # 写入机场数据
    save(AIRPORTS_FILE := os.path.join(DATA_DIR, 'airports.json'), AIRPORTS)
    print(f"✅ 机场数据库: {len(AIRPORTS)} 个机场")

    # 写入航空公司数据
    save(AIRLINES_FILE := os.path.join(DATA_DIR, 'airlines.json'), AIRLINES)
    print(f"✅ 航空公司数据库: {len(AIRLINES)} 家航司")


def save(fp, data):
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


if __name__ == '__main__':
    main()
